### ISSUE TITLE
No AnonymousUser

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#1103]
Commit:
### Steps to reproduce

From @ngehlenborg in slack:

> it seems that the AnonymousUser (id: -1) is not created on the AWS instances! @drj and @ilya - please chekc
### Observed behavior

(I don't know how you observe this)
### Expected behavior

(I don't know what you would expect)

**Comment by ngehlenborg** [comment]
Observe: log into admin console and view User instances. There is no user called "AnonymousUser" with user ID "-1".

Expected: follows directly from above.

The AnonymousUser is required for proper functioning of the system when a user is not logged in, for example to display public data sets.

**Comment by drj11** [comment]
@ngehlenborg do you know anything when that User is normally created? (I'm guessing it must be pretty magic, as grepping the code base is not very informative).

**Comment by drj11** [comment]
(and indeed, I see there is no `AnonymousUser`)

**Comment by hackdna** [comment]
No AnonymousUser in my AWS instance either.

**Comment by hackdna** [comment]
Some info on AnonymousUser object: https://docs.djangoproject.com/en/1.7/ref/contrib/auth/#anonymous-users

**Comment by hackdna** [comment]
"Once project is configured to work with django-guardian, calling syncdb management command would create User instance for anonymous user support (with name of AnonymousUser)."
and:
"The Guardian anonymous user is different to the Django Anonymous user. The Django Anonymous user does not have an entry in the database, however the Guardian anonymous user does."
http://django-guardian.readthedocs.io/en/stable/configuration.html

This means that something if failing during `syncdb`.

**Comment by drj11** [comment]
checking logs for a relatively fresh (today) AWS instance, I see

```
Notice: /Stage[main]/Refinery/Exec[syncdb]/returns: executed successfully
```

Which claims to be successful, but seems suspiciously brief to me.
It gives a line of investigation to follow though.

**Comment by hackdna** [comment]
I have provisioned a local instance from scratch using Vagrant and there was no AnonymousUser created either despite no errors reported during provisioning.

**Comment by ngehlenborg** [comment]
Maybe something we didn’t notice for a while? Maybe due to the switch from Django 1.5 to 1.6? My local instance has an AnonymousUser. It was created on 12 May 2015.

**Comment by hackdna** [comment]
Yes, it's likely. Upgrading django-guardian to the latest version (1.4.4) results in an import error when running management commands:
```
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/vagrant/refinery/manage.py", line 10, in <module>
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     execute_from_command_line(sys.argv)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     utility.execute()
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     self.fetch_command(subcommand).run_from_argv(self.argv)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     self.execute(*args, **options.__dict__)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     translation.activate('en-us')
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     return _trans.activate(language)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     _active.value = translation(language)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     default_translation = _fetch(settings.LANGUAGE_CODE)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     app = import_module(appname)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     __import__(name)
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/__init__.py", line 5, in <module>
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     from . import checks
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/checks.py", line 2, in <module>
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns:     from django.core.checks import register, Tags, Warning
==> default: Notice: /Stage[main]/Refinery::Ui/Exec[collectstatic]/returns: ImportError: cannot import name register
==> default: Error: /home/vagrant/.virtualenvs/refinery-platform/bin/python /vagrant/refinery/manage.py collectstatic --clear --noinput returned 1 instead of one of [0]
```

**Comment by scottx611x** [comment]
Running the command: `./manage.py syncdb --all` will properly create the `Anonymous_User`.

Not sure if it would be harmful to just add this flag to our Puppet `init.pp` file?

**Comment by ngehlenborg** [comment]
`Anonymous_User` or `AnonymousUser`?

**Comment by scottx611x** [comment]
@ngehlenborg My bad... `AnonymousUser`

**Comment by hackdna** [comment]
Why does that work? Have you tested this by provisioning from scratch both with Vagrant and on AWS?

**Comment by scottx611x** [comment]
Have not tested from scratch, but with an existing instance w/o an AnonymousUser. This works because the `AnonymousUser` is created upon a `post_syncdb` signal, so forcing syncdb to "see" `guardian` makes this work.

**Comment by ngehlenborg** [comment]
I can confirm that this worked for me as well (on AWS instance that was missing the `AnonymousUser`).

**Comment by scottx611x** [comment]
Note that the --help entry for the --all flags yields:   
```
--all      Makes syncdb work on all apps, even migrated ones. Be careful!
```

**Comment by hackdna** [comment]
Please note that we need to fix this for provisioning from scratch and that using `--all` is not safe: http://stackoverflow.com/questions/24569925/clarification-on-django-syncdb-all-option

**Comment by hackdna** [comment]
Upgrading django-guardian to v1.3.2 (the latest version that supports Django 1.6) results in an `AttributeError` when running `syncdb`:
```
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/vagrant/refinery/manage.py", line 10, in <module>
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     execute_from_command_line(sys.argv)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     utility.execute()
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     self.fetch_command(subcommand).run_from_argv(self.argv)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     self.execute(*args, **options.__dict__)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     output = self.handle(*args, **options)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     return self.handle_noargs(**options)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     management.call_command('migrate', **options)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     return klass.execute(*args, **defaults)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     output = self.handle(*args, **options)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     ignore_ghosts = ignore_ghosts,
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     success = migrator.migrate_many(target, workplan, database)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     result = migrator.__class__.migrate_many(migrator, target, migrations, database)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/migration/migrators.py", line 337, in migrate_many
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     interactive=self.interactive)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/db/generic.py", line 1030, in send_pending_create_signals
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     interactive=interactive)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/south/db/generic.py", line 1076, in really_send_create_signal
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     db=self.db_alias,
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     response = receiver(signal=self, sender=sender, **named)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/management/__init__.py", line 39, in create_anonymous_user
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     user.save()
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     force_update=force_update, update_fields=update_fields)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     update_fields=update_fields, raw=raw, using=using)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     response = receiver(signal=self, sender=sender, **named)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/vagrant/refinery/core/models.py", line 1882, in _add_user_to_neo4j
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     'core.read_dataset'
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:   File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/shortcuts.py", line 604, in get_objects_for_group
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns:     global_perm_set = group.permissions.values_list('codename', flat=True)
==> default: Notice: /Stage[main]/Refinery/Exec[syncdb]/returns: AttributeError: 'NoneType' object has no attribute 'permissions'
==> default: Error: /home/vagrant/.virtualenvs/refinery-platform/bin/python /vagrant/refinery/manage.py syncdb --migrate --noinput returned 1 instead of one of [0]
```

**Comment by scottx611x** [comment]
@hackdna I think i ran into this issue while on my `django 1.7` branch. The underlying issue is that there is no `public group` available before the `AnonymousUser` gets created.

**Comment by scottx611x** [comment]
To address this issue we could:

- Create user from fixture like we do `superuser`, and `guest`
- Catch the `post syncdb signal` and do the user creation through the ORM
- Have the `Public Group` created before `syncdb` is run

**Comment by hackdna** [comment]
Thanks. What are the trade-offs for each of these workarounds?

**Comment by scottx611x** [comment]
@hackdna Addressing the issue with the need of the existence of the Public Group is the real problem. Everything else is a band-aid.

**Comment by drj11** [comment]
when is the Public Group normally created? (or better, which bit of code?)

**Comment by scottx611x** [comment]
@drj11 
`init_refinery in puppet`
https://github.com/parklab/refinery-platform/blob/develop/deployment/refinery-modules/refinery/manifests/init.pp#L107

`create_public_group` in `init_refienry` command
https://github.com/parklab/refinery-platform/blob/develop/refinery/core/management/commands/init_refinery.py#L65

**Comment by drj11** [comment]
so in principle we can "just" move the `exec init_refinery` step to before the `syncdb` one.

I'll try that now.

**Comment by scottx611x** [comment]
@drj11 I don't think it is that easy because this will fail due to the Site, Group, and ExtendedGroup  models not existing yet

**Comment by hackdna** [comment]
The `syncdb` command creates all the necessary database tables and optionally runs migrations (the `--migrate` option), so it must run before any code that needs to access the database.

**Comment by scottx611x** [comment]
This order of commands addresses the issue:
`manage.py syncdb --noinput` (creates all the necessary database tables)
`manage.py migrate core` (To create ExtendedGroup Model necessary for the creation of the `Public` group)
`manage.py init_refinery <site_name> <site_url>` (Creates `Public` Group needed for AnonymousUser creation)
`manage.py migrate guardian` (Creates AnonymousUser)
`manage.py syncdb --migrate --noinput` (migrates everything else)

**Comment by drj11** [comment]
@scottx611x that's good work! thanks!

If there are no objections, I'll update puppet to do that.

**Comment by hackdna** [comment]
Can we combine the last two steps? And add comments to indicate that this is a temporary workaround (since there a big changes coming to this process in Django 1.7)?

**Comment by scottx611x** [comment]
@hackdna I'll try merging the last two steps now and see if that works

**Comment by hackdna** [comment]
Thanks, I think we can simply take out `manage.py migrate guardian` since the next line should migrate all the apps anyway. Also, which version of django-guardian are you using?

**Comment by scottx611x** [comment]
@hackdna v `1.3.2` like you proposed

**Comment by hackdna** [comment]
OK but we don't have to use that version - I was simply trying to upgrade to check if this would solve the original problem of missing AnonymousUser.

**Comment by scottx611x** [comment]
Alight, I'm mid-provision with `1.3.2` but I'll revert to 1.2.5 and try again afterwards

**Comment by hackdna** [comment]
I'm fine with 1.3.2 if it solves the problem with AnonymousUser (i.e., we should upgrade).

**Comment by scottx611x** [comment]
Merging the last two steps here:
```
manage.py migrate guardian (Creates AnonymousUser)
manage.py syncdb --migrate --noinput 
```
Into:
```
manage.py syncdb --migrate --noinput 
```
does not create the `AnonymousUser` properly

**Comment by scottx611x** [comment]
So after any `User` object gets saved we reach the line of code here: 

https://github.com/parklab/refinery-platform/blob/develop/refinery/core/models.py#L1881

Which expects the `ExtendedGroup` to be available to query, and for the Public Group to exist

This is why the changes with the extra puppet steps above work correctly

**Comment by hackdna** [comment]
I can confirm that this workaround works with the current version of django-guardian (v1.2.5) on a local Vagrant instance provisioned from scratch. One step missing is superuser creation which should be done after django-guardian migration.

Also, this needs to be tested during subsequent provisioning and on AWS. I will update the Puppet module and run the additional tests.

Finally, the problem remains that it is unclear why this works which is likely to cause problems in the future.

**Comment by hackdna** [comment]
also might be relevant: https://github.com/django-guardian/django-guardian/issues/352

**Comment by hackdna** [comment]
This has come up again (#3175), so reopening.
