### ISSUE TITLE
ProgrammingError during ELB health checks

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1397]
- Commit: fca97c904
- test.stemcellcommons.org instance
### Steps to reproduce

Spin up a new AWS stack, wait for an ELB health check
### Observed behavior

Site may become unreachable due to failing ELB health checks

```
Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)

  File "/srv/refinery-platform/refinery/config/urls.py", line 24, in <module>
    from core.views import (WorkflowViewSet, NodeViewSet,

  File "/srv/refinery-platform/refinery/core/views.py", line 36, in <module>
    from visualization_manager.views import igv_multi_species

  File "/srv/refinery-platform/refinery/visualization_manager/views.py", line 10, in <module>
    from annotation_server.utils import SUPPORTED_GENOMES

  File "/srv/refinery-platform/refinery/annotation_server/utils.py", line 5, in <module>
    genome.name for genome in GenomeBuild.objects.filter(default_build=True)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)

ProgrammingError: relation "annotation_server_genomebuild" does not exist
LINE 1: ...ion_server_genomebuild"."ucsc_equivalent_id" FROM "annotatio...
                                                             ^



<WSGIRequest
path:/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
'DJANGO_SETTINGS_MODULE': 'config.settings.aws',
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_HOST': '172.31.47.144',
'HTTP_USER_AGENT': 'ELB-HealthChecker/1.0',
'PATH_INFO': u'/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi.py/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.47.131',
'REMOTE_PORT': '17929',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://172.31.47.144/',
'SCRIPT_URL': '/',
'SERVER_ADDR': '172.31.47.144',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': '172.31.47.144',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at 172.31.47.144 Port 80</address>\n',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'test.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1473434605807443',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f730f229bf0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f730f228cd8>,
'wsgi.input': <mod_wsgi.Input object at 0x7f730f229db0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```
### Expected behavior

No error

**Comment by drj11** [comment]
It should eventually "get better" (as in, healthy), but...

There is a problem with the whole order in which components get initialised.

For example, a problem is that Apache gets installed and starts listening on the port, and is configured to find a wsgi app, well before the app itself is in place and ready to run.

**Comment by mccalluc** [comment]
From http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html:
>
HealthCheck Interval
The amount of time between health checks of an individual instance, in seconds.
Valid values: 5 to 300
Default: 30
>
Unhealthy Threshold
The number of consecutive failed health checks that must occur before declaring an EC2 instance unhealthy.
Valid values: 2 to 10
Default: 2

My understanding is that we don't actually have a pool of instances to balance between, but that we're just using ELB for HTTPS support? If that's the case, we could just set these limits higher.

**Comment by hackdna** [comment]
Actually, creating a special URL just for health checks might not be a bad idea:

"If the failure you're testing can't be fixed by replacing the front end server then it's probably not a good candidate for the health check. If your DB goes down all your web servers are going to get marked as unhealthy which is probably not what you want."
https://www.reddit.com/r/aws/comments/3dccd2/elb_health_check_best_practice/

This would also help avoid logging the health check requests.
http://stackoverflow.com/questions/32920688/how-to-setup-health-check-page-in-django

**Comment by hackdna** [comment]
Another alternative:
"Make sure that your application does not begin accepting connections until it can properly handle traffic over those connections."
https://forums.aws.amazon.com/message.jspa?messageID=141014

**Comment by hackdna** [comment]
ELB is now configured to perform health checks against the default Apache vhost.
