### ISSUE TITLE
Error importing expanded workflow into Galaxy for analysis

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1454]
- Specific code commit: c19d1f15
- Version of the web browser and OS: N/A
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Vagrant VM and AWS
- Galaxy v16.04
### Steps to reproduce
1. Install, make a trivial modification to one of the tools and save the [FastQC workflow](https://toolshed.g2.bx.psu.edu/view/stemcellcommons/fastqc_workflow/df2d7e8eacda) into Galaxy v16.04
2. Import the workflow into Refinery
3. Run an analysis using the FastQC workflow
### Observed behavior

Refinery reports that analysis has completed successfully. However, output files are not available in Refinery. Galaxy fails to run the workflow. Relevant entries from the Galaxy log:

```
galaxy.workflow.run DEBUG 2016-10-05 21:29:32,014 Workflow step 535 of invocation None invoked (0.092 ms)
galaxy.tools ERROR 2016-10-05 21:29:32,035 Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/__init__.py", line 1142, in handle_single_execution
    job, out_data = self.execute( trans, incoming=params, history=history, rerun_remap_job_id=rerun_remap_job_id, mapping_over_collection=mapping_over_collection, execution_cache=execution_cache )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/__init__.py", line 1220, in execute
    return self.tool_action.execute( self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/actions/__init__.py", line 216, in execute
    history, inp_data, inp_dataset_collections = self._collect_inputs(tool, trans, incoming, history, current_user_roles)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/actions/__init__.py", line 201, in _collect_inputs
    inp_data = self.collect_input_datasets( tool, incoming, trans, current_user_roles=current_user_roles )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/actions/__init__.py", line 149, in collect_input_datasets
    tool.visit_inputs( param_values, visitor )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/__init__.py", line 1066, in visit_inputs
    visit_input_values( self.inputs, values, callback )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/__init__.py", line 110, in visit_input_values
    callback_helper( input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/parameters/__init__.py", line 75, in callback_helper
    new_value = callback( **args )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/actions/__init__.py", line 112, in visitor
    input_datasets[ prefix + input.name ] = process_dataset( value )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/actions/__init__.py", line 61, in process_dataset
    if not data.datatype.matches_any( formats ):
AttributeError: 'RuntimeValue' object has no attribute 'datatype'
galaxy.tools.execute WARNING 2016-10-05 21:29:32,035 There was a failure executing a job for tool [toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.65] - Error executing tool: 'RuntimeValue' object has no attribute 'datatype'
galaxy.tools.execute DEBUG 2016-10-05 21:29:32,035 Executed 1 job(s) for tool toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.65 request: (20.710 ms)
galaxy.workflow.run ERROR 2016-10-05 21:29:32,037 Failed to schedule Workflow[id=74,name=FastQC - modified-2016-10-05 17:29:29.862512-04:00 (imported from API)], problem occurred on WorkflowStep[index=1,type=tool].
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 163, in invoke
    jobs = self._invoke_step( step )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 233, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/modules.py", line 1090, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
galaxy.workflow.run ERROR 2016-10-05 21:29:32,038 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 163, in invoke
    jobs = self._invoke_step( step )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 233, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/modules.py", line 1090, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
galaxy.web.framework.decorators ERROR 2016-10-05 21:29:32,040 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/lib/galaxy/web/framework/decorators.py", line 257, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/mnt/galaxy/galaxy-app/lib/galaxy/webapps/galaxy/api/workflows.py", line 204, in create
    populate_state=True,
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 22, in invoke
    return __invoke( trans, workflow, workflow_run_config, workflow_invocation, populate_state )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 163, in invoke
    jobs = self._invoke_step( step )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/run.py", line 233, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/mnt/galaxy/galaxy-app/lib/galaxy/workflow/modules.py", line 1090, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
172.31.56.0 - - [05/Oct/2016:21:29:31 +0000] "POST /api/workflows?key=52e68abf26c29a32641533053ec97637 HTTP/1.0" 500 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-48-generic"
```

Relevant entries from the Celery log:

```
2016-10-05 17:29:24 INFO     analysis_manager.tasks:77 run_analysis() - Starting analysis 'FastQC - modified 2016-10-5@17:29:23 - isytchev - None provided.'
2016-10-05 17:29:24 INFO     analysis_manager.tasks:80 run_analysis() - Starting input file import tasks for analysis 'FastQC - modified 2016-10-5@17:29:23 - isytchev - None provided.'
2016-10-05 17:29:29 DEBUG    analysis_manager.tasks:109 run_analysis() - Starting analysis execution in Galaxy
2016-10-05 17:29:29 DEBUG    galaxy_connector.galaxy_workflow:497 configure_workflow() - Configuring Galaxy workflow
2016-10-05 17:29:29 DEBUG    galaxy_connector.galaxy_workflow:521 configure_workflow() - Workflow processing: EXPANSION
2016-10-05 17:29:29 DEBUG    galaxy_connector.galaxy_workflow:73 createStepsAnnot() - Creating workflow steps annotation
2016-10-05 17:29:29 DEBUG    galaxy_connector.galaxy_workflow:460 countWorkflowSteps() - Counting workflow steps
2016-10-05 17:29:30 DEBUG    analysis_manager.tasks:232 import_analysis_in_galaxy() - Uploading analysis input files to Galaxy
2016-10-05 17:29:30 ERROR    analysis_manager.tasks:335 start_galaxy_analysis() - Analysis execution in Galaxy failed: error running Galaxy workflow for analysis 'FastQC - modified 2016-10-5@17:29:23': Unexpected response from galaxy: 500
2016-10-05 17:34:11 DEBUG    analysis_manager.tasks:341 get_galaxy_download_tasks() - Preparing to download analysis results from Galaxy
2016-10-05 17:34:12 INFO     analysis_manager.tasks:176 run_analysis() - Starting downloading of results from Galaxy for analysis 'FastQC - modified 2016-10-5@17:29:23 - isytchev - None provided.'
2016-10-05 17:34:17 INFO     core.models:1626 attach_outputs_dataset() - Results for '4fbc04e7-519e-45b7-a13a-5b0499a2d462' and text_file.txt: 0
2016-10-05 17:34:17 INFO     core.models:1635 attach_outputs_dataset() - No output file found for node '1_fastqc_results' ('568f1026-461f-4caa-8677-71f38dda357b')
2016-10-05 17:34:17 INFO     core.models:1626 attach_outputs_dataset() - Results for '4fbc04e7-519e-45b7-a13a-5b0499a2d462' and html_file.html: 0
2016-10-05 17:34:17 INFO     core.models:1635 attach_outputs_dataset() - No output file found for node '1_fastqc_report' ('b112d142-c72f-4d73-bd9f-e056537cce7f')
2016-10-05 17:34:17 INFO     data_set_manager.utils:431 _add_annotated_nodes() - 22 retrieved from data set
2016-10-05 17:34:17 INFO     data_set_manager.utils:469 _add_annotated_nodes() - 8 annotated nodes generated in 0.00940918922424
2016-10-05 17:34:17 INFO     data_set_manager.utils:494 _index_annotated_nodes() - 2 nodes for indexing
2016-10-05 17:34:17 WARNING  file_store.models:217 get_item() - FileStoreItem with UUID 'None' does not exist
2016-10-05 17:34:17 WARNING  data_set_manager.search_indexes:141 prepare() - Unable to get file store item None. No file type available.
2016-10-05 17:34:17 WARNING  file_store.models:217 get_item() - FileStoreItem with UUID 'None' does not exist
2016-10-05 17:34:17 WARNING  data_set_manager.search_indexes:141 prepare() - Unable to get file store item None. No file type available.
2016-10-05 17:34:17 INFO     data_set_manager.utils:503 _index_annotated_nodes() - 2 nodes indexed in 0.121575117111
2016-10-05 17:34:17 DEBUG    core.models:1527 rename_results() - Renaming analysis results
2016-10-05 17:34:18 INFO     core.models:1523 send_email() - Emailed completion message: status 'SUCCESS' to 'isytchev@hsph.harvard.edu' for analysis 'FastQC - modified 2016-10-5@17:29:23' with UUID '4fbc04e7-519e-45b7-a13a-5b0499a2d462'
2016-10-05 17:34:18 INFO     analysis_manager.tasks:214 run_analysis() - Analysis 'FastQC - modified 2016-10-5@17:29:23 - isytchev - None provided.' finished successfully
2016-10-05 17:34:18 INFO     core.utils:185 update_annotation_sets_neo4j() - Updating annotation sets for "" (If username is empty, updates for all users) in Neo4J.
```
### Expected behavior

Workflow should run successfully in Galaxy and its outputs should be downloaded into Refinery.

**Comment by hackdna** [comment]
[ChIP-seq workflows](https://toolshed.g2.bx.psu.edu/view/stemcellcommons/chipseq_workflows/f9ffbe563402) get uploaded into Galaxy successfully but analyses fail to run with the following error message displayed for the first step: "Parameter index requires a value, but has no legal values defined." 

Relevant Galaxy log entries:
```
galaxy.jobs.runners ERROR 2016-10-06 12:49:17,439 (683) Failure preparing job
Traceback (most recent call last):
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/jobs/runners/__init__.py", line 169, in prepare_job
    job_wrapper.prepare()
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/jobs/__init__.py", line 885, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/evaluation.py", line 63, in set_compute_environment
    visit_input_values( self.tool.inputs, incoming, validate_inputs )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/__init__.py", line 104, in visit_input_values
    visit_input_values( input.cases[ values[ '__current_case__' ] ].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/__init__.py", line 110, in visit_input_values
    callback_helper( input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/__init__.py", line 75, in callback_helper
    new_value = callback( **args )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/evaluation.py", line 61, in validate_inputs
    value = input.from_json( value, request_context, context )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/basic.py", line 915, in from_json
    raise ValueError( "Parameter %s requires a value, but has no legal values defined." % self.name )
ValueError: Parameter index requires a value, but has no legal values defined.
galaxy.jobs.runners DEBUG 2016-10-06 12:49:17,442 Job [684] queued (31.231 ms)
galaxy.jobs.handler INFO 2016-10-06 12:49:17,469 (684) Job dispatched
galaxy.jobs.runners ERROR 2016-10-06 12:49:17,493 (684) Failure preparing job
Traceback (most recent call last):
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/jobs/runners/__init__.py", line 169, in prepare_job
    job_wrapper.prepare()
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/jobs/__init__.py", line 885, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/evaluation.py", line 63, in set_compute_environment
    visit_input_values( self.tool.inputs, incoming, validate_inputs )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/__init__.py", line 104, in visit_input_values
    visit_input_values( input.cases[ values[ '__current_case__' ] ].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/__init__.py", line 110, in visit_input_values
    callback_helper( input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/__init__.py", line 75, in callback_helper
    new_value = callback( **args )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/evaluation.py", line 61, in validate_inputs
    value = input.from_json( value, request_context, context )
  File "/Users/isytchev/code/galaxy/live/lib/galaxy/tools/parameters/basic.py", line 915, in from_json
    raise ValueError( "Parameter %s requires a value, but has no legal values defined." % self.name )
ValueError: Parameter index requires a value, but has no legal values defined.
```
Relevant Celery log entries:
```
2016-10-06 12:37:57 DEBUG    analysis_manager.tasks:109 run_analysis() - Starting analysis execution in Galaxy
2016-10-06 12:37:57 DEBUG    galaxy_connector.galaxy_workflow:497 configure_workflow() - Configuring Galaxy workflow
2016-10-06 12:37:57 DEBUG    galaxy_connector.galaxy_workflow:521 configure_workflow() - Workflow processing: EXPANSION
2016-10-06 12:37:57 DEBUG    galaxy_connector.galaxy_workflow:73 createStepsAnnot() - Creating workflow steps annotation
2016-10-06 12:37:57 DEBUG    galaxy_connector.galaxy_workflow:460 countWorkflowSteps() - Counting workflow steps
2016-10-06 12:37:57 DEBUG    analysis_manager.tasks:232 import_analysis_in_galaxy() - Uploading analysis input files to Galaxy
2016-10-06 12:38:04 DEBUG    analysis_manager.tasks:135 run_analysis() - Analysis 'TF ChIP-Seq analysis using MACS2: hg19 - modified 2016-10-6@12:44:53 - guest - None provided.' pending in Galaxy
2016-10-06 12:38:10 DEBUG    analysis_manager.tasks:135 run_analysis() - Analysis 'TF ChIP-Seq analysis using MACS2: hg19 - modified 2016-10-6@12:44:53 - guest - None provided.' pending in Galaxy
2016-10-06 12:38:16 DEBUG    analysis_manager.tasks:135 run_analysis() - Analysis 'TF ChIP-Seq analysis using MACS2: hg19 - modified 2016-10-6@12:44:53 - guest - None provided.' pending in Galaxy
2016-10-06 12:39:06 ERROR    core.models:1377 galaxy_progress() - Analysis 'TF ChIP-Seq analysis using MACS2: hg19 - modified 2016-10-6@12:44:53 - guest - None provided.' failed in Galaxy
```

**Comment by hackdna** [comment]
The single input [RNA-seq workflow](https://toolshed.g2.bx.psu.edu/view/stemcellcommons/rnaseq_workflows/ba1b76257fa5) runs successfully.

**Comment by hackdna** [comment]
The original error appears to be due to a [bug in Galaxy](https://github.com/galaxyproject/galaxy/issues/2437) that was fixed after [release v16.04](https://github.com/galaxyproject/galaxy/releases/tag/v16.04). However, updating to the [latest commit in release_16.04 branch](https://github.com/galaxyproject/galaxy/commit/224c2126c73617ec906abc1e08d5f5a7548633b1) results in a different error.

Celery log:
```
2016-10-06 16:46:43 INFO     analysis_manager.tasks:77 run_analysis() - Starting analysis 'FastQC - modified 2016-10-6@16:56:47 - guest - None provided.'
2016-10-06 16:46:43 INFO     analysis_manager.tasks:80 run_analysis() - Starting input file import tasks for analysis 'FastQC - modified 2016-10-6@16:56:47 - guest - None provided.'
2016-10-06 16:46:49 DEBUG    analysis_manager.tasks:109 run_analysis() - Starting analysis execution in Galaxy
2016-10-06 16:46:49 DEBUG    galaxy_connector.galaxy_workflow:497 configure_workflow() - Configuring Galaxy workflow
2016-10-06 16:46:49 DEBUG    galaxy_connector.galaxy_workflow:521 configure_workflow() - Workflow processing: EXPANSION
2016-10-06 16:46:49 DEBUG    galaxy_connector.galaxy_workflow:73 createStepsAnnot() - Creating workflow steps annotation
2016-10-06 16:46:49 DEBUG    galaxy_connector.galaxy_workflow:460 countWorkflowSteps() - Counting workflow steps
2016-10-06 16:46:49 DEBUG    analysis_manager.tasks:232 import_analysis_in_galaxy() - Uploading analysis input files to Galaxy
2016-10-06 16:47:22 DEBUG    analysis_manager.tasks:341 get_galaxy_download_tasks() - Preparing to download analysis results from Galaxy
2016-10-06 16:47:22 INFO     file_store.tasks:43 create() - Creating FileStoreItem using source 'http://192.168.50.1:8080/datasets/c90b0c8884a69d5c/display?to_ext=txt'
2016-10-06 16:47:22 INFO     file_store.models:389 set_filetype() - File type is set to 'zip'
2016-10-06 16:47:22 INFO     file_store.tasks:52 create() - FileStoreItem created with UUID e239d6d3-5a75-4824-ab1a-53f79db593df
2016-10-06 16:47:22 INFO     file_store.tasks:43 create() - Creating FileStoreItem using source 'http://192.168.50.1:8080/datasets/0a104a51724928c1/display?to_ext=txt'
2016-10-06 16:47:22 INFO     file_store.models:389 set_filetype() - File type is set to 'txt'
2016-10-06 16:47:22 INFO     file_store.tasks:52 create() - FileStoreItem created with UUID 232029c8-186b-4314-9129-2deffb8462a2
2016-10-06 16:47:22 INFO     analysis_manager.tasks:176 run_analysis() - Starting downloading of results from Galaxy for analysis 'FastQC - modified 2016-10-6@16:56:47 - guest - None provided.'
2016-10-06 16:47:28 ERROR    analysis_manager.tasks:193 run_analysis() - Analysis '%s' failed while downloading results from  Galaxy
```

Galaxy log:
```
192.168.50.50 - - [06/Oct/2016:16:57:30 -0400] "GET /datasets/c90b0c8884a69d5c/display?to_ext=txt HTTP/1.1" 500 - "-" "python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-49-generic"
Error - <type 'exceptions.Exception'>: Unknown parameter type (<type 'NoneType'>)
URL: http://192.168.50.1:8080/datasets/c90b0c8884a69d5c/display?to_ext=txt
File '/Users/isytchev/code/galaxy/live/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/Users/isytchev/code/galaxy/live/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/Users/isytchev/code/galaxy/live/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/Users/isytchev/code/galaxy/live/lib/galaxy/web/framework/base.py', line 131 in __call__
  return self.handle_request( environ, start_response )
File '/Users/isytchev/code/galaxy/live/lib/galaxy/web/framework/base.py', line 190 in handle_request
  body = method( trans, **kwargs )
File '/Users/isytchev/code/galaxy/live/lib/galaxy/webapps/galaxy/controllers/dataset.py', line 245 in display
  return data.datatype.display_data(trans, data, preview, filename, to_ext, offset=offset, ck_size=ck_size, **kwd)
File '/Users/isytchev/code/galaxy/live/lib/galaxy/datatypes/data.py', line 353 in display_data
  return self._archive_composite_dataset( trans, data, **kwd )
File '/Users/isytchev/code/galaxy/live/lib/galaxy/datatypes/data.py', line 235 in _archive_composite_dataset
  params = util.Params( kwd )
File '/Users/isytchev/code/galaxy/live/lib/galaxy/util/__init__.py', line 683 in __init__
  self.__dict__[ key ] = sanitize_param( value )
File '/Users/isytchev/code/galaxy/live/lib/galaxy/util/__init__.py', line 488 in sanitize_param
  raise Exception('Unknown parameter type (%s)' % ( type( value ) ))
Exception: Unknown parameter type (<type 'NoneType'>)


CGI Variables
-------------
  CONTENT_LENGTH: '0'
  HTTP_ACCEPT: '*/*'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_HOST: '192.168.50.1:8080'
  HTTP_USER_AGENT: 'python-requests/2.7.0 CPython/2.7.6 Linux/3.13.0-49-generic'
  PATH_INFO: '/datasets/c90b0c8884a69d5c/display'
  QUERY_STRING: 'to_ext=txt'
  REMOTE_ADDR: '192.168.50.50'
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '0.0.0.0'
  SERVER_PORT: '8080'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x10fb70f50>
  controller_action_key: u'web.dataset.display'
  is_api_request: False
  paste.cookies: (<SimpleCookie: >, '')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x10fb70ed0>
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x1106ace50>
  paste.parsed_querystring: ([('to_ext', 'txt')], 'to_ext=txt')
  paste.recursive.forward: <paste.recursive.Forwarder from />
  paste.recursive.include: <paste.recursive.Includer from />
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from />
  paste.recursive.script_name: ''
  paste.throw_errors: True
  request_id: '7ec225638c0711e69a6734363bd33a42'
  webob._parsed_query_vars: (GET([(u'to_ext', u'txt')]), 'to_ext=txt')
  wsgi process: 'Multithreaded'
```

**Comment by hackdna** [comment]
[Question: multiple output with html format in Galaxy Unknown parameter type (<type 'NoneType'>)](https://biostar.usegalaxy.org/p/19142/)
[Question: multiple output with html format in Galaxy Unknown parameter type (<type 'NoneType'>)](https://github.com/galaxyproject/galaxy/issues/2874)
It seems that we don’t have the problem anymore with our test instance (16.07)
[Problem downloading HTML datasets](http://dev.list.galaxyproject.org/Problem-downloading-HTML-datasets-td4670034.html)

**Comment by hackdna** [comment]
[Galaxy 16.04 API: Invoking a workflow that includes tools passed as RuntimeValue objects throws exception](https://github.com/galaxyproject/galaxy/issues/2437)

**Comment by scottx611x** [comment]
@hackdna I believe this can be closed since we are no longer creating copies of our workflows and importing them into Galaxy

**Comment by hackdna** [comment]
OK
