### ISSUE TITLE
ISATab DataSets seem to lack their symlinked isatab files on AWS instances brought up from snapshots

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1455]
- Specific code commit: 31ce211bd9d377e7e7ed3a0edb85e1157c8389ff
- Version of the web browser and OS: N/A
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://beta.stemcellcommons.org/
### Steps to reproduce
1. Open the [Details page](https://beta.stemcellcommons.org/data_sets/218cb1fd-a8ae-4dca-9df3-50b606f9c87b/#/details/) for a DataSet imported from an isatab (most, if not all, are on beta)
2. Generally, when this is done there is a link to said dataset's isa-tab file under the **Meta Data** header, but this is not the case...
   ![screen shot 2016-10-06 at 5 09 54 pm](https://cloud.githubusercontent.com/assets/5629547/19170791/c4ce4288-8be7-11e6-9b5b-a362e5bbcee7.png)
3. Although, if a user uploads an isatab to the site now, it seems like things are working fine...
   ![screen shot 2016-10-06 at 5 11 44 pm](https://cloud.githubusercontent.com/assets/5629547/19170855/0186b96c-8be8-11e6-8d30-f56bbf6fa961.png)
### Observed behavior
- It seems that older ISATab DataSets do not know about where their isatab files reside, whereas newly imported ISATab Datsets do...
- @ngehlenborg hypothesized that it may be due to some broken symlinks???
- Clicking on the **Import Into Own Space** button in the details tab _should_ fetch the relative path to the ISATab zip, but here the url built for a "re-import" looks like:
  **https://beta.stemcellcommons.org../isa-tab/isa_9886_731436.zip**
### Expected behavior
- For All Datasets that have been imported from an IsaTab to know about their zip files so we can re-import them

@hackdna if this is indeed a symlink issue could this have been broken when restoring from a snapshot??

**Comment by scottx611x** [comment]
I guess it's also good to note that the erring datasets were all imported using the `process_isatab` management command. I don't think this is the cause of the error though as I've been using said command locally pretty consistently and the datasets imported properly display their isatab links

**Comment by scottx611x** [comment]
I could reproduce this behavior on an AWS instance brought up with an RDS snapshot.

It seems that isatabs are imported to a directory that does not get encapsulated in the snapshot, and are then symlinked into the file_store directory.

@drj11 Does it make sense that these symlinks could become lost?

**Comment by drj11** [comment]
(the symlink or the file) yes.

The AWS EC2 snapshot doesn't do the entire system, it only does the data-specific disk.

So it's plausible that either:
- something is accidentally ending up in the wrong directory; or,
- the AWS config has missed configuring a directory.

Is there a description of what happens when an `isa_tab` is uploaded? (I'll dig around anyway)

**Comment by hackdna** [comment]
My guess is that ISA-archives somehow get uploaded to a temp dir outside the data volume and then symlinked into the file store instead of getting moved or copied.

**Comment by scottx611x** [comment]
Related to: https://github.com/refinery-platform/refinery-platform/issues/315

**Comment by scottx611x** [comment]
@jkmarx I was still able to reproduce this issue is this past round of manual testing. 

I know I watched you and confirmed that it was working but it may have just been an edge case or the clause from above: `whereas newly imported ISATab Datasets do [know their location on disk]...`

Just wanted to document.

**Comment by scottx611x** [comment]
Just documenting that this issue was observed again today after bringing up a test site from `beta.stemcellcommons` snapshots.

IsaTab datasets that are encapsulated in snapshots don't work properly but newly uploaded IsaTab datasets work fine.

Traceback seen when navigating to the file browser for a "bad" isatab dataset:
```
Internal Server Error: /data_sets/218cb1fd-a8ae-4dca-9df3-50b606f9c87b/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/refinery-platform/refinery/core/views.py", line 333, in data_set
    context_instance=RequestContext(request))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 898, in render
    output = self.filter_expression.resolve(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 596, in resolve
    obj = self.var.resolve(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 734, in resolve
    value = self._resolve_lookup(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 788, in _resolve_lookup
    current = current()
  File "/srv/refinery-platform/refinery/file_store/models.py", line 306, in get_file_size
    return self.datafile.size
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/fields/files.py", line 74, in _get_size
    return self.storage.size(self.name)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/files/storage.py", line 285, in size
    return os.path.getsize(self.path(name))
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/data/media/file_store/d1/c4/isa_9909_558276.zip'
```

**Comment by scottx611x** [comment]
I haven't been able to reproduce this for awhile. 
I think that things go awry when you specify incompatible RDS/EBS snapshots in `deployment/aws-config/config.yaml`
Closing
