### ISSUE TITLE
Error entering duplicate group name when creating a new group

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1477]
- Specific code commit: 7969dc1
- Version of the web browser and OS: all
- Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): all
### Steps to reproduce

Create a group with a name that already exists
### Observed behavior

Error in Django logs:

```
Traceback (most recent call last):

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch
    response = method(request, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/tastypie/resources.py", line 1341, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))

  File "/srv/refinery-platform/refinery/core/api.py", line 2008, in obj_create
    new_ext_group.save()

  File "/srv/refinery-platform/refinery/core/models.py", line 1866, in save
    super(ExtendedGroup, self).save(*args, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 572, in save_base
    self._save_parents(cls, using, update_fields)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 597, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)

  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)

IntegrityError: duplicate key value violates unique constraint "auth_group_name_key"
DETAIL:  Key (name)=(Tenen Lab) already exists.

<WSGIRequest
path:/api/v1/extended_groups/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1008158846.1448040184',
'csrftoken': '',
'sessionid': ''},
META:{'CONTENT_LENGTH': '20',
'CONTENT_TYPE': 'application/json;charset=utf-8',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': u'',
'DJANGO_SETTINGS_MODULE': 'config.settings.aws',
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/plain, */*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1008158846.1448040184; csrftoken=; sessionid=',
'HTTP_HOST': 'test.stemcellcommons.org',
'HTTP_REFERER': 'https://test.stemcellcommons.org/collaboration/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0',
'HTTP_X_CSRFTOKEN': '',
'HTTP_X_FORWARDED_FOR': '134.174.140.208',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/api/v1/extended_groups/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi.py/api/v1/extended_groups/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.33.0',
'REMOTE_PORT': '5958',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/api/v1/extended_groups/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://test.stemcellcommons.org/api/v1/extended_groups/',
'SCRIPT_URL': '/api/v1/extended_groups/',
'SERVER_ADDR': '172.31.40.244',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'test.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '<address>Apache/2.4.7 (Ubuntu) Server at test.stemcellcommons.org Port 80</address>\n',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'test.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1476381680889798',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f871704f7f0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f87201ba7b0>,
'wsgi.input': <mod_wsgi.Input object at 0x7f8716db84b0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```
### Expected behavior

Duplicate group name should not result in a server error (exception should be handled). Users should be notified about the duplicate group name and allowed to to enter a different one.

**Comment by hackdna** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle IntegrityError when creating a group with a duplicate name](https://trello.com/c/VdIFDQnk/336-handle-integrityerror-when-creating-a-group-with-a-duplicate-name)
