### ISSUE TITLE
Provenance Graph Fails to Load

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1654]
Specific code commit: afe887dee960aa2e34837512072a6d7d6fd11304
Version of the web browser and OS: Chrome Version 56.0.2924.87 / 10.11.6
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):
https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1. Open in the file browser Data Set 13880: Genome-wide maps of binding sites of Nanog-like and Mxtx2 in blastula stage zebrafish embryos OR Data Set 11610: Transcription factor binding during intestinal cell differentiation [TFB]  OR Data Set 16410: Depletion of RUNX1/ETO in t(8;21) AML cells leads to genome-wide changes in chromatin structure and transcription factor binding (ChIP-seq) 
2. Select the provenance graph - file display

### Observed behavior
Fails to load.
Console Error:
```VM6045:1 Uncaught SyntaxError: Unexpected token : in JSON at position 5593
    at JSON.parse (<anonymous>)
    at https://test.stemcellcommons.org/static/js/provvis/provvis-init.js:3:3278
    at Array.forEach (native)
    at w (https://test.stemcellcommons.org/static/js/provvis/provvis-init.js:3:2854)
    at D (https://test.stemcellcommons.org/static/js/provvis/provvis-init.js:3:7815)
    at Object.run (https://test.stemcellcommons.org/static/js/provvis/provvis-init.js:3:7946)
    at https://test.stemcellcommons.org/static/js/provvis/provvis.js:3:6067
    at Object.<anonymous> (https://test.stemcellcommons.org/static/vendor/d3/d3.min.js:1:11277)
    at Object.t (https://test.stemcellcommons.org/static/vendor/d3/d3.min.js:1:1565)
    at XMLHttpRequest.u (https://test.stemcellcommons.org/static/vendor/d3/d3.min.js:1:10137)
(anonymous)	@	provvis-init.js:295
w	@	provvis-init.js:272
D	@	provvis-init.js:645
run	@	provvis-init.js:675
(anonymous)	@	provvis.js:423
(anonymous)	@	d3.min.js:1
t	@	d3.min.js:1
u	@	d3.min.js:1```

### Expected behavior
Should load without errors.

**Comment by scottx611x** [comment]
I can reproduce this error in: 
`Chrome Version 54.0.2840.59 (64-bit) & Firefox Version 52.0.1 (64-bit) in Ubuntu 16.04 LTS`

**Comment by scottx611x** [comment]
Locally w/ unminified code this error looks like
```
Uncaught SyntaxError: Unexpected token d in JSON at position 4854
    at JSON.parse (<anonymous>)
    at provvis-init.js:296
    at Array.forEach (<anonymous>)
    at extractWorkflows (provvis-init.js:273)
    at runInitPrivate (provvis-init.js:646)
    at Object.run (provvis-init.js:676)
    at provvis.js:427
    at Object.<anonymous> (d3.min.js:1)
    at Object.t (d3.min.js:1)
    at XMLHttpRequest.u (d3.min.js:1)
```

**Comment by scottx611x** [comment]
Also this issue seems to be due to the fact that we are handling JSON deserialization client-side here: https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/ui/source/js/provvis/provvis-init.js#L275-L292

**Comment by mccalluc** [comment]
> JSON deserialization

(Actually, the API is returning a serialized python dict, and then the js tries to munge that into json with a bunch of regexes. Ideally, return real json from the server, and then clientside deserialization shouldn't be a problem.)

**Comment by mccalluc** [comment]
For reference, here's the path the data we need to change follows:
```
data_set_monitor.js:
	DataSetMonitor.prototype._refreshAnalyses = function() {
	  var self = this;
	  self.analyses = null;
	  self._analysisApiClient.getList(function() {
		self.analyses = self._analysisApiClient.list;

contents.js:
  dataSetMonitor = new DataSetMonitor(dataSetUuid, REFINERY_API_BASE_URL, csrf_token, dataSetMonitorCommands);

contents.js:
  if (arguments.query == provVisQuery && provvis.get() instanceof provvisDecl.ProvVis === false) {
	provvis.run(currentStudyUuid, dataSetMonitor.analyses.objects, arguments.response);
  }

provvis.js:
var provvis = (function (  // eslint-disable-line no-unused-vars
  $, provvisDecl, provvisInit, provvisLayout, provvisMotifs, provvisRender
) {
  ...
  return {
    run: function (studyUuid, studyAnalyses, solrResponse) {
      runProvVisPrivate(studyUuid, studyAnalyses, solrResponse);
    },

provvis.js:
  var runProvVisPrivate = function (studyUuid, studyAnalyses, solrResponse) {
    showProvvisLoaderIcon();

    /* Only allow one instance of ProvVis. */
    if (vis instanceof provvisDecl.ProvVis === false) {
      var url = '/api/v1/node/?study__uuid=' + studyUuid +
        '&format=json&limit=0';
      var analysesData = studyAnalyses.filter(function (a) {
        return a.status === 'SUCCESS';
      });

      /* Parse json. */
      d3.json(url, function (error, data) {
        ...
        ...
        vis.graph = provvisInit.run(data, analysesData, solrResponse);

provvis-init.js:
  return {
    run: function (data, analysesData, solrResponse) {
      return runInitPrivate(data, analysesData, solrResponse);
    }
  };

provvis-init.js:
  var runInitPrivate = function (data, analysesData, solrResponse) {
    ...
    extractWorkflows(analysesData);

provvis-init.js:
	var extractWorkflows = function (analysesData) {
    analysesData.forEach(function (a) {
      /* Prepare for json format. */
      var prepareJSON = function (wfCpy) {/* ugly */};
  	  var text = prepareJSON(a.workflow_copy);
      var wfData = JSON.parse(text);
```
