### ISSUE TITLE
Collaboration - Send Invite Bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1655]
Specific code commit: 5965130ef900c1d66e56bcd0d851d6e254cbeb8c
Version of the web browser and OS: Version 56.0.2924.87 / 10.11.6
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):
https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1. Create a new group
2. On the collaboration page, send an invite for a group you manage

### Observed behavior
Network:
Header
```Request URL:https://test.stemcellcommons.org/api/v1/invitations/?format=json
Request Method:POST
Status Code:500 INTERNAL SERVER ERROR
Remote Address:54.165.184.72:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Connection:keep-alive
Content-Type:application/json
Date:Wed, 29 Mar 2017 13:55:15 GMT
Server:Apache/2.4.7 (Ubuntu)
transfer-encoding:chunked
Vary:Cookie
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:46
Content-Type:application/json;charset=UTF-8
Cookie:sessionid=4c4xbcrnn6fadttvza6zg6dtrvkupqkt; _ga=GA1.2.1149280071.1461676876; csrftoken=N5vrafvQfPXsUZSfocHijrTOelhLtN5H
Host:test.stemcellcommons.org
Origin:https://test.stemcellcommons.org
Referer:https://test.stemcellcommons.org/collaboration/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
X-CSRFToken:N5vrafvQfPXsUZSfocHijrTOelhLtN5H
Query String Parameters
view source
view URL encoded
format:json
Request Payload
view source
{email: "jentek.jm@gmail.com", group_id: 143}
email
:
"jentek.jm@gmail.com"
group_id
:
143
```
Response: 
```
{"error_message": "Sorry, this request could not be processed. Please try again later."}

```

Console Error:
```
angular.js:14110 TypeError: f.generateAlertMessage is not a function
    at collaboration.js:109
    at angular.js:16606
    at m.$eval (angular.js:17913)
    at m.$digest (angular.js:17727)
    at m.$apply (angular.js:18021)
    at angular.js:18322
    at e (angular.js:6035)
    at angular.js:6314
(anonymous) @ angular.js:14110
(anonymous) @ angular.js:10633
(anonymous) @ angular.js:16614
$eval @ angular.js:17913
$digest @ angular.js:17727
$apply @ angular.js:18021
(anonymous) @ angular.js:18322
e @ angular.js:6035
(anonymous) @ angular.js:6314
```

### Expected behavior
No error, should be able to invite.

**Comment by jkmarx** [comment]
I couldn't reproduce the bug locally, so I went back on test.
<img width="1437" alt="screen shot 2017-03-29 at 10 26 14 am" src="https://cloud.githubusercontent.com/assets/9956764/24459669/2c0fd456-146a-11e7-9450-ca8b8772c696.png">

**Comment by jkmarx** [comment]
Issue is the aws config.yaml was not updated correctly. Will fix.

**Comment by scottx611x** [comment]
The issue remains after updating the `DEFAULT_FROM_EMAIL` & `SERVER_EMAIL` settings to proper values

**Comment by hackdna** [comment]
It's unlikely that a missing JS function would be a result of server misconfiguration. Refinery runs in prod mode on AWS. Is this also the case when testing on Vagrant VM?

**Comment by jkmarx** [comment]
```[Wed Mar 29 13:45:30.473926 2017] [:error] [pid 11281:tid 140565201729280] 2017-03-29 13:45:30 ERROR    django.request.tastypie:280 _handle_500() - Internal Server Error: /api/v1/invitations/
[Wed Mar 29 13:45:30.474159 2017] [:error] [pid 11281:tid 140565201729280] Traceback (most recent call last):
[Wed Mar 29 13:45:30.474266 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
[Wed Mar 29 13:45:30.474390 2017] [:error] [pid 11281:tid 140565201729280]     response = callback(request, *args, **kwargs)
[Wed Mar 29 13:45:30.474514 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list
[Wed Mar 29 13:45:30.474631 2017] [:error] [pid 11281:tid 140565201729280]     return self.dispatch('list', request, **kwargs)
[Wed Mar 29 13:45:30.474778 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch
[Wed Mar 29 13:45:30.474874 2017] [:error] [pid 11281:tid 140565201729280]     response = method(request, **kwargs)
[Wed Mar 29 13:45:30.474986 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 1341, in post_list
[Wed Mar 29 13:45:30.475164 2017] [:error] [pid 11281:tid 140565201729280]     updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
[Wed Mar 29 13:45:30.475284 2017] [:error] [pid 11281:tid 140565201729280]   File "/vagrant/refinery/core/api.py", line 1921, in obj_create
[Wed Mar 29 13:45:30.475382 2017] [:error] [pid 11281:tid 140565201729280]     self.send_email(request, inv)
[Wed Mar 29 13:45:30.475495 2017] [:error] [pid 11281:tid 140565201729280]   File "/vagrant/refinery/core/api.py", line 1874, in send_email
[Wed Mar 29 13:45:30.475605 2017] [:error] [pid 11281:tid 140565201729280]     email.send()
[Wed Mar 29 13:45:30.475714 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/message.py", line 286, in send
[Wed Mar 29 13:45:30.475825 2017] [:error] [pid 11281:tid 140565201729280]     return self.get_connection(fail_silently).send_messages([self])
[Wed Mar 29 13:45:30.475940 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 92, in send_messages
[Wed Mar 29 13:45:30.476042 2017] [:error] [pid 11281:tid 140565201729280]     new_conn_created = self.open()
[Wed Mar 29 13:45:30.476154 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 50, in open
[Wed Mar 29 13:45:30.476265 2017] [:error] [pid 11281:tid 140565201729280]     self.connection = connection_class(self.host, self.port, **connection_params)
[Wed Mar 29 13:45:30.476374 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Wed Mar 29 13:45:30.476483 2017] [:error] [pid 11281:tid 140565201729280]     (code, msg) = self.connect(host, port)
[Wed Mar 29 13:45:30.476604 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Wed Mar 29 13:45:30.476711 2017] [:error] [pid 11281:tid 140565201729280]     self.sock = self._get_socket(host, port, self.timeout)
[Wed Mar 29 13:45:30.476819 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Wed Mar 29 13:45:30.476927 2017] [:error] [pid 11281:tid 140565201729280]     return socket.create_connection((host, port), timeout)
[Wed Mar 29 13:45:30.477036 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Wed Mar 29 13:45:30.477154 2017] [:error] [pid 11281:tid 140565201729280]     raise err
[Wed Mar 29 13:45:30.477272 2017] [:error] [pid 11281:tid 140565201729280] error: [Errno 111] Connection refused
[Wed Mar 29 13:45:30.480481 2017] [:error] [pid 11281:tid 140565201729280] 2017-03-29 13:45:30 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /api/v1/invitations/
[Wed Mar 29 13:45:30.480644 2017] [:error] [pid 11281:tid 140565201729280] Traceback (most recent call last):
[Wed Mar 29 13:45:30.480764 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Wed Mar 29 13:45:30.480883 2017] [:error] [pid 11281:tid 140565201729280]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Mar 29 13:45:30.480999 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
[Wed Mar 29 13:45:30.481124 2017] [:error] [pid 11281:tid 140565201729280]     return view_func(*args, **kwargs)
[Wed Mar 29 13:45:30.481242 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 249, in wrapper
[Wed Mar 29 13:45:30.481392 2017] [:error] [pid 11281:tid 140565201729280]     return self._handle_500(request, e)
[Wed Mar 29 13:45:30.481531 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 280, in _handle_500
[Wed Mar 29 13:45:30.481645 2017] [:error] [pid 11281:tid 140565201729280]     extra={'status_code': response_code, 'request': request})
[Wed Mar 29 13:45:30.481801 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
[Wed Mar 29 13:45:30.481945 2017] [:error] [pid 11281:tid 140565201729280]     self._log(ERROR, msg, args, **kwargs)
[Wed Mar 29 13:45:30.482076 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
[Wed Mar 29 13:45:30.482245 2017] [:error] [pid 11281:tid 140565201729280]     self.handle(record)
[Wed Mar 29 13:45:30.482393 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
[Wed Mar 29 13:45:30.482491 2017] [:error] [pid 11281:tid 140565201729280]     self.callHandlers(record)
[Wed Mar 29 13:45:30.482622 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
[Wed Mar 29 13:45:30.482723 2017] [:error] [pid 11281:tid 140565201729280]     hdlr.handle(record)
[Wed Mar 29 13:45:30.482851 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
[Wed Mar 29 13:45:30.482970 2017] [:error] [pid 11281:tid 140565201729280]     self.emit(record)
[Wed Mar 29 13:45:30.483087 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/log.py", line 132, in emit
[Wed Mar 29 13:45:30.483194 2017] [:error] [pid 11281:tid 140565201729280]     connection=self.connection())
[Wed Mar 29 13:45:30.483341 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/__init__.py", line 98, in mail_admins
[Wed Mar 29 13:45:30.483437 2017] [:error] [pid 11281:tid 140565201729280]     mail.send(fail_silently=fail_silently)
[Wed Mar 29 13:45:30.483547 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/message.py", line 286, in send
[Wed Mar 29 13:45:30.483660 2017] [:error] [pid 11281:tid 140565201729280]     return self.get_connection(fail_silently).send_messages([self])
[Wed Mar 29 13:45:30.483783 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 92, in send_messages
[Wed Mar 29 13:45:30.483905 2017] [:error] [pid 11281:tid 140565201729280]     new_conn_created = self.open()
[Wed Mar 29 13:45:30.484051 2017] [:error] [pid 11281:tid 140565201729280]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 50, in open
[Wed Mar 29 13:45:30.484181 2017] [:error] [pid 11281:tid 140565201729280]     self.connection = connection_class(self.host, self.port, **connection_params)
[Wed Mar 29 13:45:30.484313 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Wed Mar 29 13:45:30.484444 2017] [:error] [pid 11281:tid 140565201729280]     (code, msg) = self.connect(host, port)
[Wed Mar 29 13:45:30.484568 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Wed Mar 29 13:45:30.484696 2017] [:error] [pid 11281:tid 140565201729280]     self.sock = self._get_socket(host, port, self.timeout)
[Wed Mar 29 13:45:30.484820 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Wed Mar 29 13:45:30.484841 2017] [:error] [pid 11281:tid 140565201729280]     return socket.create_connection((host, port), timeout)
[Wed Mar 29 13:45:30.484851 2017] [:error] [pid 11281:tid 140565201729280]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Wed Mar 29 13:45:30.484860 2017] [:error] [pid 11281:tid 140565201729280]     raise err
[Wed Mar 29 13:45:30.484868 2017] [:error] [pid 11281:tid 140565201729280] error: [Errno 111] Connection refused
[Wed Mar 29 13:45:30.487788 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843] mod_wsgi (pid=11281): Exception occurred processing WSGI script '/vagrant/refinery/config/wsgi_prod.py'.
[Wed Mar 29 13:45:30.487975 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843] Traceback (most recent call last):
[Wed Mar 29 13:45:30.488099 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Wed Mar 29 13:45:30.488251 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     response = self.get_response(request)
[Wed Mar 29 13:45:30.488406 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
[Wed Mar 29 13:45:30.488543 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Wed Mar 29 13:45:30.488661 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 231, in handle_uncaught_exception
[Wed Mar 29 13:45:30.488799 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     'request': request
[Wed Mar 29 13:45:30.488927 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
[Wed Mar 29 13:45:30.489101 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     self._log(ERROR, msg, args, **kwargs)
[Wed Mar 29 13:45:30.489208 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
[Wed Mar 29 13:45:30.489343 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     self.handle(record)
[Wed Mar 29 13:45:30.489490 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
[Wed Mar 29 13:45:30.489779 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     self.callHandlers(record)
[Wed Mar 29 13:45:30.489957 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
[Wed Mar 29 13:45:30.490080 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     hdlr.handle(record)
[Wed Mar 29 13:45:30.490239 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
[Wed Mar 29 13:45:30.490356 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     self.emit(record)
[Wed Mar 29 13:45:30.490572 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/log.py", line 132, in emit
[Wed Mar 29 13:45:30.490689 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     connection=self.connection())
[Wed Mar 29 13:45:30.490807 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/__init__.py", line 98, in mail_admins
[Wed Mar 29 13:45:30.490939 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     mail.send(fail_silently=fail_silently)
[Wed Mar 29 13:45:30.491043 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/message.py", line 286, in send
[Wed Mar 29 13:45:30.491173 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     return self.get_connection(fail_silently).send_messages([self])
[Wed Mar 29 13:45:30.491302 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 92, in send_messages
[Wed Mar 29 13:45:30.491446 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     new_conn_created = self.open()
[Wed Mar 29 13:45:30.491564 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 50, in open
[Wed Mar 29 13:45:30.491675 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     self.connection = connection_class(self.host, self.port, **connection_params)
[Wed Mar 29 13:45:30.491795 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Wed Mar 29 13:45:30.491923 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     (code, msg) = self.connect(host, port)
[Wed Mar 29 13:45:30.492040 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Wed Mar 29 13:45:30.492169 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     self.sock = self._get_socket(host, port, self.timeout)
[Wed Mar 29 13:45:30.492276 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Wed Mar 29 13:45:30.492404 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     return socket.create_connection((host, port), timeout)
[Wed Mar 29 13:45:30.492570 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Wed Mar 29 13:45:30.492699 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843]     raise err
[Wed Mar 29 13:45:30.492828 2017] [:error] [pid 11281:tid 140565201729280] [remote 192.168.50.1:26843] error: [Errno 111] Connection refused```

**Comment by jkmarx** [comment]
Server error log above from prod mode.

```
Object {
data: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">…able↵in the server error log.</p>↵</body></html>↵", 
status: 500, 
config: Object, 
statusText: "Internal Server Error", 
headers: function}
config: Objectdata: Objectheaders: Objectmethod: "POST"paramSerializer: function 
(a)params: ObjecttransformRequest: Array(1)transformResponse: Array(1)
url: "/api/v1/invitations/"__proto__: Objectdata: "
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">↵<html><head>↵<title>500 Internal Server Error</title>↵</head><body>↵
<h1>Internal Server Error</h1>↵
<p>The server encountered an internal error or↵
misconfiguration and was unable to complete↵
your request.</p>↵
<p>Please contact the server administrator at ↵
 [no address given] to inform them of the time this error occurred,↵
 and the actions you performed just before this error.</p>↵
<p>More information about this error may be available↵in the server error log.</p>↵
</body></html>↵
"headers: function (d)status: 500statusText: "Internal Server Error"__proto__: Object
(anonymous) @ angular.js:14110
(anonymous) @ collaboration.js:110
(anonymous) @ angular.js:16606
$eval @ angular.js:17913
$digest @ angular.js:17727
$apply @ angular.js:18021
(anonymous) @ angular.js:18322
e @ angular.js:6035
(anonymous) @ angular.js:6314
```

**Comment by scottx611x** [comment]
This error was just due to the initial misconfiguration when bringing up the stack. 

I've fixed this now.

Error was: 
```
[Wed Mar 29 13:59:11.851330 2017] [:error] [pid 8199:tid 140103444997888] SMTPDataError: (554, 'Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: refinery-registration@example.org')
```

**Comment by hackdna** [comment]
There is a `ConnectionError` that can be raised on line 1874 in refinery/core/api.py (`email.send()`). This should be handled and an appropriate message returned with the response to notify user of failure.
