### ISSUE TITLE
Provisioning failure with NoMethodError in Puppet

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1847]
* Specific code commit: f38072ed
* Version of the web browser and OS: N/A
* Environment where the error occurred: Vagrant and AWS

### Steps to reproduce
Pull the latest code from `develop` and either provision in using Vagrant or create a stack on AWS

### Observed behavior
Error message on AWS:
```
+ sudo su -c /usr/local/bin/librarian-puppet install ubuntu
/var/lib/gems/1.9.1/gems/puppet_forge-2.2.5/lib/puppet_forge.rb:10:in `host=': undefined method `[]' for #<URI::HTTPS:0x000000017e0e18> (NoMethodError)
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge/repo_v3.rb:14:in `initialize'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge.rb:163:in `new'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge.rb:163:in `repo'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge.rb:152:in `manifests'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/dependency.rb:155:in `cache_manifests!'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/dependency.rb:151:in `manifests'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:159:in `block in resolving_dependency_map_find_manifests'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:172:in `block (2 levels) in scope_resolving_dependency'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:186:in `block in scope_checking_manifests'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:185:in `scope_checking_manifests'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:171:in `block in scope_resolving_dependency'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:170:in `scope_resolving_dependency'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:158:in `resolving_dependency_map_find_manifests'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:65:in `do_resolve'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:50:in `resolve'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver.rb:23:in `resolve'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:31:in `run'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/action/resolve.rb:10:in `run'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:104:in `resolve!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:68:in `install'
	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/bin/librarian-puppet:7:in `<top (required)>'
	from /usr/local/bin/librarian-puppet:23:in `load'
	from /usr/local/bin/librarian-puppet:23:in `<main>'
+ /usr/bin/puppet apply --modulepath=/srv/refinery-platform/deployment/modules /srv/refinery-platform/deployment/manifests/aws.pp
Error: Could not find class refinery for ip-172-31-55-73.ec2.internal on node ip-172-31-55-73.ec2.internal
```

Error message in Vagrant:
```
==> default: /var/lib/gems/1.9.1/gems/puppet_forge-2.2.5/lib/puppet_forge.rb:10:in `host='
==> default: :
==> default: undefined method `[]' for #<URI::HTTPS:0x00000002e92008>
==> default:  (
==> default: NoMethodError
==> default: )
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge/repo_v3.rb:14:in `initialize'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge.rb:163:in `new'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge.rb:163:in `repo'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/source/forge.rb:152:in `manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/dependency.rb:155:in `cache_manifests!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/dependency.rb:151:in `manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:159:in `block in resolving_dependency_map_find_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:172:in `block (2 levels) in scope_resolving_dependency'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:186:in `block in scope_checking_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:185:in `scope_checking_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:171:in `block in scope_resolving_dependency'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:170:in `scope_resolving_dependency'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:158:in `resolving_dependency_map_find_manifests'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:65:in `do_resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:50:in `resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/resolver.rb:23:in `resolve'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:31:in `run'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/action/resolve.rb:10:in `run'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:104:in `resolve!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:68:in `install'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
==> default: 	from /var/lib/gems/1.9.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
==> default: 	from /var/lib/gems/1.9.1/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
==> default: 	from /var/lib/gems/1.9.1/gems/librarian-puppet-2.2.3/bin/librarian-puppet:7:in `<top (required)>'
==> default: 	from /usr/local/bin/librarian-puppet:23:in `load'
==> default: 	from /usr/local/bin/librarian-puppet:23:in `<main>'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### Expected behavior
Provisioning should succeed

**Comment by hackdna** [comment]
Fixed in [v2.2.6 of puppet_forge gem](https://github.com/puppetlabs/forge-ruby/blob/master/CHANGELOG.md#v226---2017-06-27)
