### ISSUE TITLE
Database connection error when launching AWS stack with custom RDS_SUPERUSER_PASSWORD

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1990]
* Specific code commit: 0aaa1a94
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
1. Set `RDS_SUPERUSER_PASSWORD` to a custom value
1. Launch a new stack

### Observed behavior
Error messages in `cloud-init-output.log`:
```
+ PASSWORD=password bin/ensure-postgresql-role
psql: FATAL:  password authentication failed for user "root"
FATAL:  password authentication failed for user "root"
+ bin/ensure-postgresql-database
psql: FATAL:  password authentication failed for user "root"
FATAL:  password authentication failed for user "root"
...
Notice: /Stage[main]/Refinery/Exec[migrate]/returns: Traceback (most recent call last):
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/srv/refinery-platform/refinery/manage.py", line 10, in <module>
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     execute_from_command_line(sys.argv)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     utility.execute()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.fetch_command(subcommand).run_from_argv(self.argv)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.execute(*args, **options.__dict__)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     output = self.handle(*args, **options)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     executor = MigrationExecutor(connection, self.migration_progress_callback)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in __init__
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.loader = MigrationLoader(self.connection)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.build_graph()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 183, in build_graph
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.applied_migrations = recorder.applied_migrations()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.ensure_schema()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 167, in cursor
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     cursor = utils.CursorWrapper(self._cursor(), self)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 138, in _cursor
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.ensure_connection()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.connect()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.connect()
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 122, in connect
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     self.connection = self.get_new_connection(conn_params)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     connection = Database.connect(**conn_params)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:   File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 179, in connect
Notice: /Stage[main]/Refinery/Exec[migrate]/returns:     connection_factory=connection_factory, async=async)
Notice: /Stage[main]/Refinery/Exec[migrate]/returns: django.db.utils.OperationalError: FATAL:  password authentication failed for user "refinery"
Notice: /Stage[main]/Refinery/Exec[migrate]/returns: FATAL:  password authentication failed for user "refinery"
Error: /home/ubuntu/.virtualenvs/refinery-platform/bin/python /srv/refinery-platform/refinery/manage.py migrate --noinput returned 1 instead of one of [0]
Error: /Stage[main]/Refinery/Exec[migrate]/returns: change from notrun to 0 failed: /home/ubuntu/.virtualenvs/refinery-platform/bin/python /srv/refinery-platform/refinery/manage.py migrate --noinput returned 1 instead of one of [0]
```

### Expected behavior
No database errors in `cloud-init-output.log`

**Comment by scottx611x** [comment]
@hackdna Looks like we have the `RDS_SUPERUSER_PASSWORD` hardcoded here in [stack.py](https://github.com/refinery-platform/refinery-platform/blob/develop/deployment/stack.py#L193)
