### ISSUE TITLE
Intermittent Travis CI build failure in test_visualization_container_launch_IGV

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1996]
* Specific code commit: 6cb90c8
* Version of the web browser and OS: N/A
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Travis CI

### Steps to reproduce
Run a Travis CI build

### Observed behavior
Build fails intermittently with the following error message:
```
FAIL: test_visualization_container_launch_IGV (tool_manager.tests.VisualizationToolLaunchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/tool_manager/tests.py", line 2038, in test_visualization_container_launch_IGV
    wait_until_class_visible(self.browser, "igv-track-label", MAX_WAIT)
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/selenium_testing/utils.py", line 147, in wait_until_class_visible
    "wait period.".format(search_class, wait_duration))
AssertionError: Element with class: 'igv-track-label' was not visible within the 60 second wait period.
```

### Expected behavior
* No build failures

**Comment by mccalluc** [comment]
Hopefully fixed if we remove selenium tests.
