### ISSUE TITLE
"study_uuid: AND assay_uuid:" solr syntax error

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2063]
Don't think this would cause the Shivdesani instance to go down, but we should figure out where this is coming from.

**Comment by mccalluc** [comment]
could be contents.js:
```
var client = new SolrClient(solrRoot,
          solrSelectEndpoint,
          csrf_token,
          "django_ct:data_set_manager.node",
          "(study_uuid:" + currentStudyUuid + " AND assay_uuid:" + currentAssayUuid + ")",
          clientCommands);
```

That seems to be the only place this particular subquery, with no additions, is generated.

**Comment by scottx611x** [comment]
@mccalluc I would be more ok with the first 2 of your bullet points than the last one. 

<details>
<summary>Relevant solr log entry</summary>

```
2017-08-30 17:47:50.200 ERROR (qtp945299648-15) [   x:data_set_manager] o.a.s.c.SolrCore org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse '(study_uuid: AND assay_uuid:)': Encountered " <AND> "AND "" at line 1, column 13.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    <NUMBER> ...
    
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:215)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:251)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2068)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:669)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:462)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:214)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:179)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```
</details>

**Comment by jkmarx** [comment]
@mccalluc When were these errors generated?

**Comment by mccalluc** [comment]
We had seen this in the logs, but we couldn't/didn't connect it to anything on the front end: I don't think we figured out what behaviors produced these errors -- we just saw that they had occurred in the past.

**Comment by jkmarx** [comment]
Fixed by default when removing the file browser one code in issue #2202
