### ISSUE TITLE
all files download CSV fails on test if unfiltered (1000+ rows)

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2064]
* Specific code commit: a679b9904cc8d9c199cd4122f15b502f931aaab9
* Version of the web browser and OS: mac ff
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):  test production

### Steps to reproduce
Please list all the actions and the input data used:

1. https://test.stemcellcommons.org/files_download?fq=&sort=
2. 500

@scottx611x : I look like a large number of rows are necessary to reproduce this. Before I start trying to upload all those files locally, could we get the logs from the server? Is that some I should already know how to do?

**Comment by scottx611x** [comment]
@mccalluc I can grab the logs or we could do it as a pair? Either way just grab me when you get around to addressing this.

**Comment by scottx611x** [comment]
```
[Thu Aug 31 14:46:35.504683 2017] [:error] [pid 11555:tid 139707721045760] 2017-08-31 14:46:35 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /files_download
[Thu Aug 31 14:46:35.504826 2017] [:error] [pid 11555:tid 139707721045760] Traceback (most recent call last):
[Thu Aug 31 14:46:35.504878 2017] [:error] [pid 11555:tid 139707721045760]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Thu Aug 31 14:46:35.504925 2017] [:error] [pid 11555:tid 139707721045760]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Aug 31 14:46:35.504970 2017] [:error] [pid 11555:tid 139707721045760]   File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 42, in user_files_csv
[Thu Aug 31 14:46:35.505015 2017] [:error] [pid 11555:tid 139707721045760]     writer.writerow(row)
[Thu Aug 31 14:46:35.505059 2017] [:error] [pid 11555:tid 139707721045760] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u2013' in position 4: ordinal not in range(128)
[Thu Aug 31 14:46:35.734607 2017] [:error] [pid 11555:tid 139707721045760] 2017-08-31 14:46:35 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /files_download
[Thu Aug 31 14:46:35.734721 2017] [:error] [pid 11555:tid 139707721045760] Traceback (most recent call last):
[Thu Aug 31 14:46:35.734771 2017] [:error] [pid 11555:tid 139707721045760]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
[Thu Aug 31 14:46:35.734838 2017] [:error] [pid 11555:tid 139707721045760]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Aug 31 14:46:35.734884 2017] [:error] [pid 11555:tid 139707721045760]   File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 42, in user_files_csv
[Thu Aug 31 14:46:35.734931 2017] [:error] [pid 11555:tid 139707721045760]     writer.writerow(row)
[Thu Aug 31 14:46:35.734976 2017] [:error] [pid 11555:tid 139707721045760] UnicodeEncodeError: 'ascii' codec can't encode character u'\\u2013' in position 4: ordinal not in range(128)
```

**Comment by mccalluc** [comment]
\u2013 is just en-dash, so not something esoteric, and a good thing to catch.
