### ISSUE TITLE
Unit test errors and failures in data_set_manager

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2067]
* Specific code commit: cf979ec
* Version of the web browser and OS: n/a
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Vagrant

### Steps to reproduce
1. Bring up a new Vagrant environment
1. Run: ```(refinery-platform)vagrant@refinery:/vagrant/refinery$ ./manage.py test```
1. Run: ```(refinery-platform)vagrant@refinery:/vagrant/refinery$ ./manage.py test data_set_manager.tests```

### Observed behavior
Step 2 hangs for a long time and after interruption produces the following output:
```
.2017-08-29 18:51:56 DEBUG    pyvirtualdisplay.abstractdisplay:90 redirect_display() - DISPLAY=:1001
^CE
======================================================================
ERROR: test_create_valid_tool (tool_manager.tests.VisualizationToolLaunchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/refinery/tool_manager/tests.py", line 1951, in setUp
    SeleniumTestBaseGeneric.setUp(self)
  File "/vagrant/refinery/selenium_testing/utils.py", line 25, in setUp
    self.browser.maximize_window()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 581, in maximize_window
    self.execute(command, {"windowHandle": "current"})
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 488, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

======================================================================
FAIL: test_prepare (data_set_manager.tests.NodeIndexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/tests.py", line 1735, in test_prepare
    'workflow_output': None})
AssertionError: {'REFINERY_ANALYSIS_UUID_#_#_s': 'N/A', 'data_set_uuid': u'46c974b5-a23c-4d6f-93 [truncated]... != {'REFINERY_TYPE_#_#_s': u'', 'measurement_source_Characteristics_generic_s': '', [truncated]...
  {'REFINERY_ANALYSIS_UUID_#_#_s': 'N/A',
-  'REFINERY_DOWNLOAD_URL_s': u'/media/file_store/#/#/test_file_vvZVWqI.txt',
?                                                              --------

+  'REFINERY_DOWNLOAD_URL_s': u'/media/file_store/#/#/test_file.txt',
   'REFINERY_FILETYPE_#_#_s': None,
   'REFINERY_NAME_#_#_s': 'http://example.com/fake.txt',
   'REFINERY_SUBANALYSIS_#_#_s': -1,
   'REFINERY_TYPE_#_#_s': u'',
   'REFINERY_WORKFLOW_OUTPUT_#_#_s': 'N/A',
   'analysis_uuid': None,
   'assay_uuid': u'7983757a-5d88-460c-ae6e-1ba2479c5f5b',
   'data_set_uuid': u'46c974b5-a23c-4d6f-9360-a703e9d8bd51',
   u'django_ct': u'data_set_manager.node',
   u'django_id': u'#',
   'file_uuid': u'b8a1a34e-937c-4c96-979e-430499ccc801',
   'filename_Characteristics_generic_s': u'fake.txt',
   'genome_build': None,
   u'id': u'data_set_manager.node.#',
   'is_annotation': False,
   'measurement_Characteristics_generic_s': '',
   'measurement_accession_Characteristics_generic_s': '',
   'measurement_source_Characteristics_generic_s': '',
   'name': u'http://example.com/fake.txt',
   'platform_Characteristics_generic_s': '',
   'species': None,
   'study_uuid': u'061ed62b-3153-4eba-83cf-3046497b93dc',
   'subanalysis': None,
   'technology_Characteristics_generic_s': 'whizbang',
   'technology_accession_Characteristics_generic_s': '',
   'technology_source_Characteristics_generic_s': '',
   'text': u'',
   'type': u'',
   'uuid': u'fd3bcc46-0a93-479c-ae01-7e0aec3ff7d7',
   'workflow_output': None}

----------------------------------------------------------------------
Ran 360 tests in 9138.895s

FAILED (failures=1, errors=1)
Destroying test database for alias 'default'...
```

Step 3 also results in errors and failures:
```
Creating test database for alias 'default'...
2017-08-29 21:24:17 INFO     data_set_manager.isa_tab_parser:1109 get_dataset_name() - Supplied path "refinery/data_set_manager/test-data/MTBLS1.zip" is not a directory. Assuming ISArchive file.
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:1144 get_dataset_name() - Unable to extract assumed ISArchive file "refinery/data_set_manager/test-data/MTBLS1.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 1114, in get_dataset_name
    with ZipFile(path, 'r') as zip:
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'refinery/data_set_manager/test-data/MTBLS1.zip'
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:1151 get_dataset_name() - Unable to identify ISArchive file in "refinery/data_set_manager/test-data/MTBLS1.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 1148, in get_dataset_name
    investigation_file_name = glob.glob("%s/i*.txt" % path).pop()
IndexError: pop from empty list
2017-08-29 21:24:17 INFO     data_set_manager.isa_tab_parser:944 run() - Supplied path "refinery/data_set_manager/test-data/MTBLS1.zip" is not a directory. Assuming ISArchive file.
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:979 run() - Unable to extract assumed ISArchive file "refinery/data_set_manager/test-data/MTBLS1.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 949, in run
    with ZipFile(path, 'r') as zip:
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'refinery/data_set_manager/test-data/MTBLS1.zip'
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:985 run() - Unable to identify ISArchive file in "refinery/data_set_manager/test-data/MTBLS1.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 982, in run
    investigation_file_name = glob.glob("%s/i*.txt" % path).pop()
IndexError: pop from empty list
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:532 parse_isatab() - *** print_tb:
Creating public group 'Public' for Refinery. Edit 'REFINERY_PUBLIC_GROUP_NAME' in your settings to choose another name or 'REFINERY_PUBLIC_GROUP_ID' to choose another id.Successfully created group 'Public'.  File "/vagrant/refinery/data_set_manager/tasks.py", line 523, in parse_isatab
    preisa_archive=pre_isa_archive
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 986, in run
    raise exception
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:534 parse_isatab() - None
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:535 parse_isatab() - *** print_exception:
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/tasks.py", line 523, in parse_isatab
    preisa_archive=pre_isa_archive
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 986, in run
    raise exception
IndexError: pop from empty list
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:541 parse_isatab() - None
.2017-08-29 21:24:17 INFO     data_set_manager.isa_tab_parser:1109 get_dataset_name() - Supplied path "refinery/data_set_manager/test-data/MTBLS112.zip" is not a directory. Assuming ISArchive file.
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:1144 get_dataset_name() - Unable to extract assumed ISArchive file "refinery/data_set_manager/test-data/MTBLS112.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 1114, in get_dataset_name
    with ZipFile(path, 'r') as zip:
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'refinery/data_set_manager/test-data/MTBLS112.zip'
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:1151 get_dataset_name() - Unable to identify ISArchive file in "refinery/data_set_manager/test-data/MTBLS112.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 1148, in get_dataset_name
    investigation_file_name = glob.glob("%s/i*.txt" % path).pop()
IndexError: pop from empty list
2017-08-29 21:24:17 INFO     data_set_manager.isa_tab_parser:944 run() - Supplied path "refinery/data_set_manager/test-data/MTBLS112.zip" is not a directory. Assuming ISArchive file.
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:979 run() - Unable to extract assumed ISArchive file "refinery/data_set_manager/test-data/MTBLS112.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 949, in run
    with ZipFile(path, 'r') as zip:
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'refinery/data_set_manager/test-data/MTBLS112.zip'
2017-08-29 21:24:17 ERROR    data_set_manager.isa_tab_parser:985 run() - Unable to identify ISArchive file in "refinery/data_set_manager/test-data/MTBLS112.zip".
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 982, in run
    investigation_file_name = glob.glob("%s/i*.txt" % path).pop()
IndexError: pop from empty list
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:532 parse_isatab() - *** print_tb:
  File "/vagrant/refinery/data_set_manager/tasks.py", line 523, in parse_isatab
    preisa_archive=pre_isa_archive
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 986, in run
    raise exception
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:534 parse_isatab() - None
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:535 parse_isatab() - *** print_exception:
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/tasks.py", line 523, in parse_isatab
    preisa_archive=pre_isa_archive
  File "/vagrant/refinery/data_set_manager/isa_tab_parser.py", line 986, in run
    raise exception
IndexError: pop from empty list
2017-08-29 21:24:17 ERROR    data_set_manager.tasks:541 parse_isatab() - None
............2017-08-29 21:24:18 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:18 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:18 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:18 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:18 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:18 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.2017-08-29 21:24:19 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:19 DEBUG    core.serializers:105 _get_file_extension() - FileStoreItem matching query does not exist.
.....2017-08-29 21:24:20 ERROR    data_set_manager.models:484 get_file_store_item() - FileStoreItem matching query does not exist.
...F2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '4b71b0c1-ffdc-42c7-b940-f287b2bda85f'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile 'a6/2f/test_file_dY0kHBi.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'b87f2a93-b2d4-4b98-8869-e165ef497069'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'feb84de3-2e69-430c-b7cf-8415170bc956'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'd3baba01-f9cd-4060-b563-f82e77d29499'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '1c71973d-5b5f-4bb4-ad9f-dfe8175365e0'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '19249297-71aa-490c-bed4-23e733047e75'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '53647f4a-2ebe-41ed-ba7b-eb89ad699dd1'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:20 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '341be196-d89c-4606-85e0-aeee90531093'
2017-08-29 21:24:20 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:20 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'b63a0515-51a6-4fd1-b645-4bebd30a356c'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '48bd1479-36eb-4b57-b327-1c5d529b7e55'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '53c28ea6-99c5-49ec-9cd1-49adbc32c93b'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '14df4b15-763c-4233-887f-6367be008f12'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'ebeee340-5985-4cff-b131-d933d8eec421'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 ERROR    data_set_manager.models:556 get_relative_file_store_item_url() - FileStoreItem matching query does not exist.
2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'abc19e89-deda-425d-8c25-abae2f675940'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 ERROR    data_set_manager.utils:862 get_owner_from_assay() - Study matching query does not exist.
2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '14e63202-7270-498c-9b71-fc5f3d2adcae'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '2c603d62-29dc-42ff-8d99-8c0c783c17f9'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '5eb09c3c-c50a-4d57-8a6b-cf831aded2a6'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:21 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '1eeecf45-6f2e-4beb-ac4b-bc3f85076c0d'
2017-08-29 21:24:21 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:21 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '997d58ae-be9a-4cae-bbcd-d3eac1787ca6'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'a2b9dddc-eecb-403a-8acc-833d9a3d16b4'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'e7d2cb93-ab1b-4b8b-8012-7e183602bfa1'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'dddf9507-7fe7-4a54-a245-97ca6f4386c1'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '3d33bb41-253a-413a-ba86-9f6265a33114'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID '7a809237-7006-48ac-874b-fb7cdd613279'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.2017-08-29 21:24:22 DEBUG    file_store.models:663 _delete_datafile() - Deleting FileStoreItem with UUID 'e6dc6642-7a28-4db0-b75a-0bb3113f3da7'
2017-08-29 21:24:22 DEBUG    file_store.models:446 delete_datafile() - Deleting datafile '50/85/test_file_a.txt'
2017-08-29 21:24:22 INFO     file_store.models:455 delete_datafile() - Datafile deleted
.
======================================================================
FAIL: test_prepare (data_set_manager.tests.NodeIndexTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/tests.py", line 1735, in test_prepare
    'workflow_output': None})
AssertionError: {'measurement_source_Characteristics_generic_s': '', 'data_set_uuid': u'38359009 [truncated]... != {'REFINERY_TYPE_#_#_s': u'', 'measurement_source_Characteristics_generic_s': '', [truncated]...
  {'REFINERY_ANALYSIS_UUID_#_#_s': 'N/A',
-  'REFINERY_DOWNLOAD_URL_s': u'/media/file_store/#/#/test_file_#.txt',
?                                                              --

+  'REFINERY_DOWNLOAD_URL_s': u'/media/file_store/#/#/test_file.txt',
   'REFINERY_FILETYPE_#_#_s': None,
   'REFINERY_NAME_#_#_s': 'http://example.com/fake.txt',
   'REFINERY_SUBANALYSIS_#_#_s': -1,
   'REFINERY_TYPE_#_#_s': u'',
   'REFINERY_WORKFLOW_OUTPUT_#_#_s': 'N/A',
   'analysis_uuid': None,
   'assay_uuid': u'd44fd90f-e36b-4110-882b-230c477263fb',
   'data_set_uuid': u'38359009-4011-44b6-b020-69eb94ff9a26',
   u'django_ct': u'data_set_manager.node',
   u'django_id': u'#',
   'file_uuid': u'4b71b0c1-ffdc-42c7-b940-f287b2bda85f',
   'filename_Characteristics_generic_s': u'fake.txt',
   'genome_build': None,
   u'id': u'data_set_manager.node.#',
   'is_annotation': False,
   'measurement_Characteristics_generic_s': '',
   'measurement_accession_Characteristics_generic_s': '',
   'measurement_source_Characteristics_generic_s': '',
   'name': u'http://example.com/fake.txt',
   'platform_Characteristics_generic_s': '',
   'species': None,
   'study_uuid': u'ed262b23-64e6-410b-abc4-2187fe208fcc',
   'subanalysis': None,
   'technology_Characteristics_generic_s': 'whizbang',
   'technology_accession_Characteristics_generic_s': '',
   'technology_source_Characteristics_generic_s': '',
   'text': u'',
   'type': u'',
   'uuid': u'1a67d79b-302d-4dd3-bd76-a44e0a38705f',
   'workflow_output': None}

----------------------------------------------------------------------
Ran 55 tests in 5.656s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

### Expected behavior
No errors or failures when running tests

**Comment by mccalluc** [comment]
```
-  'REFINERY_DOWNLOAD_URL_s': u'/media/file_store/#/#/test_file_vvZVWqI.txt',
?                                                              --------
+  'REFINERY_DOWNLOAD_URL_s': u'/media/file_store/#/#/test_file.txt',
```
I'm trying to clean up these strings before doing the comparison, but I had assumed there were be a digit somewhere in the random suffix. That is not necessarily true.

**Comment by mccalluc** [comment]
@hackdna : Does #2070 fix this, or do you want to see more work done?

**Comment by hackdna** [comment]
Are the full test suite runs still hanging on Vagrant?

**Comment by mccalluc** [comment]
Not for me, at least just now:
```
$ ./manage.py test
...
======================================================================
FAIL: test_visualization_container_launch_IGV (tool_manager.tests.VisualizationToolLaunchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/refinery/tool_manager/tests.py", line 2038, in test_visualization_container_launch_IGV
    wait_until_class_visible(self.browser, "igv-track-label", MAX_WAIT)
  File "/vagrant/refinery/selenium_testing/utils.py", line 147, in wait_until_class_visible
    "wait period.".format(search_class, wait_duration))
AssertionError: Element with class: 'igv-track-label' was not visible within the 60 second wait period.

----------------------------------------------------------------------
Ran 405 tests in 296.277s

FAILED (failures=1)
Creating public group 'Public' for Refinery. Edit 'REFINERY_PUBLIC_GROUP_NAME' in your settings to choose another name or 'REFINERY_PUBLIC_GROUP_ID' to choose another id.Successfully created group 'Public'.Destroying test database for alias 'default'...
```
The remaining error is covered by #1996. Closing.

**Comment by hackdna** [comment]
Still hanging for me at `.2017-09-05 11:13:04 DEBUG    pyvirtualdisplay.abstractdisplay:90 redirect_display() - DISPLAY=:1001` - for over 25 minutes. Commit 24dd3c6.

**Comment by hackdna** [comment]
The same happens when running tests on `manage.py test tool_manager` or any other test suite that contains Selenium tests. The simplest case to reproduce this problem (based on `SeleniumTestBaseGeneric.setUp()`):
```python
>>> from pyvirtualdisplay import Display
>>> display = Display(visible=0, size=(1366, 768))
>>> display.start()
<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1366x768x24', ':1001'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1366x768x24', ':1001'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>
>>> from selenium import webdriver
>>> browser = webdriver.Firefox()
>>> browser.maximize_window()
...
<hang>
```
Commenting out [`self.browser.maximize_window()`](https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/selenium_testing/utils.py#L26) allows the test suites to run to completion.

There is [an open issue](https://github.com/mozilla/geckodriver/issues/703) for it in the geckodriver repo.

This another reason to separate integration tests from unit tests.

**Comment by scottx611x** [comment]
@hackdna Has #2181 addressed this issue?

**Comment by hackdna** [comment]
Yes though it's more of a workaround than a fix.

**Comment by hackdna** [comment]
I can not longer reproduce the original problem, so closing.
