### ISSUE TITLE
HTTP 500 error when accessing data set API

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2078]
* Specific code commit: 24dd3c6
* Version of the web browser and OS: n/a
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): any

### Steps to reproduce
Access data set/assays API endpoint for any data set (`/api/v1/data_sets/<data_set_uuid>/assays/?format=json`)

### Observed behavior
HTTP 500 error:
```
Internal Server Error: /api/v1/data_sets/1f3165e3-5aca-4f07-9334-42f23b727512/assays/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/core/api.py", line 791, in get_assays
    assays = data_set.get_assays()
AttributeError: 'DataSet' object has no attribute 'get_assays'
```

### Expected behavior
No error

**Comment by scottx611x** [comment]
`DataSet.get_assays()` existed in `v1.5.8`: https://github.com/refinery-platform/refinery-platform/blob/v1.5.8/refinery/core/models.py#L700

**Comment by hackdna** [comment]
```
$ git log -S get_assays refinery/core/models.py
commit 9e45ed90cf3698df687512f9f2995a5fbb2c8d86
Author: mccalluc <mccalluc@users.noreply.github.com>
Date:   Fri Aug 18 14:14:33 2017 -0400

    get_assays is buggy, and both are unused (#2016)

commit bc6fc06d43bb243319da819a21126649e64a6d0a
Author: Fritz Lekschas <service@lekschas.de>
Date:   Fri Jan 22 17:37:13 2016 -0500

    Added to helper methods to be able to quickly access all studies or assay of a data set.
```
