### ISSUE TITLE
Internal server error in NodeSet API

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2229]
* Specific code commit: 8d80f47 (v1.5.8)
* Version of the web browser and OS: unknown
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): beta.stemcellcommons.org

### Steps to reproduce
Unknown, error report received by email.

### Observed behavior
Server log:
```
Internal Server Error: /api/v1/nodeset/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch
    response = method(request, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/tastypie/resources.py", line 1341, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
  File "/srv/refinery-platform/refinery/core/api.py", line 1199, in obj_create
    study_uuid = match.group()
AttributeError: 'NoneType' object has no attribute 'group'

Request repr():
<WSGIRequest
path:/api/v1/nodeset/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.413897679.1502909599',
'_gat': '1',
'_gid': 'GA1.2.1672840673.1507829281',
'csrftoken': <removed>,
'sessionid': <removed>},
META:{'CONTENT_LENGTH': '178',
'CONTENT_TYPE': 'application/json',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <removed>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/javascript, */*; q=0.01',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'sessionid=<removed>; _gat=1; csrftoken=<removed>; _ga=GA1.2.413897679.1502909599; _gid=GA1.2.1672840673.1507829281',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_ORIGIN': 'https://beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/user/files/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
'HTTP_X_CSRFTOKEN': <removed>,
'HTTP_X_FORWARDED_FOR': '134.174.140.132',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
'PATH_INFO': u'/api/v1/nodeset/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/api/v1/nodeset/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.57.72',
'REMOTE_PORT': '9317',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/api/v1/nodeset/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/api/v1/nodeset/',
'SCRIPT_URL': '/api/v1/nodeset/',
'SERVER_ADDR': '172.31.59.253',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1507831630037689',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f454e50cb30>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f454e349dc8>,
'wsgi.input': <mod_wsgi.Input object at 0x7f454e38a070>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No internal server error

**Comment by scottx611x** [comment]
I don't think we use `NodeSets` anymore? 

Probably related to https://github.com/refinery-platform/refinery-platform/issues/1853

**Comment by ngehlenborg** [comment]
Also remove NodeSet API.
