### ISSUE TITLE
Tool launch error on 1.6.0

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2256]
Geoff hit this on the 8e52d991125378cf test instance: Just another failure mode I hadn't anticipated, but hopefully not hard to address.
```
[Fri Oct 20 10:43:52.462571 2017] [:error] [pid 23747:tid 139803437475584] 2017-10-20 10:43:52 
```
```
django.request:231 handle_uncaught_exception() - Internal Server Error: /
Traceback (most recent call last):
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 68, in _proxy_view
  return view(request, url=url)
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
  return self.dispatch(request, *args, **kwargs)
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 82, in dispatch
  response = super(HttpProxy, self).dispatch(request, *args, **kwargs)
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
  return handler(request, *args, **kwargs)
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 141, in get
  return self.get_response()
File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 166, in get_response
  response = urllib.request.urlopen(request)
File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
  return _opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 404, in open
  response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 422, in _open
  '_open', req)
File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
  result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
  return self.do_open(httplib.HTTPConnection, req)
File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
  r = h.getresponse(buffering=True)
File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
  response.begin()
File "/usr/lib/python2.7/httplib.py", line 444, in begin
  version, status, reason = self._read_status()
File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
  line = self.fp.readline(_MAXLINE + 1)
File "/usr/lib/python2.7/socket.py", line 476, in readline
  data = self._sock.recv(self._rbufsize)
[Fri Oct 20 10:43:52.462688 2017] [:error] [pid 23747:tid 139803437475584] error: [Errno 104] Connection reset by peer
```

**Comment by mccalluc** [comment]
The instance is out of date: In the latest version, that error should be caught by https://github.com/refinery-platform/django_docker_engine/blob/f25e7d80cc96d318a2d08c890faa6a5f909995d2/django_docker_engine/proxy.py#L81, but the deployed code looks like:
```
    def _proxy_view(self, request, container_name, url):
        self.logger.log(container_name, url)
        try:
            client = DockerClientWrapper(self.data_dir)
            container_url = client.lookup_container_url(container_name)
            view = HttpProxy.as_view(base_url=container_url)
            return view(request, url=url)
        except (NotFound, BadStatusLine) as e:
            logger.info(
                'Normal transient error. '
                'Container: %s, Exception: %s', container_name, e)
            view = self._please_wait_view_factory(self.content).as_view()
            return view(request)
```

That was fixed in Refinery by #2213 on October 5, but 1.6.0 was complete and merged back to dev on October 2.

Process-wise, it may have been overlooked because the work was "done" in django_docker, but the version number in refinery wasn't incremented until after the release.

Closing.
