### ISSUE TITLE
"Exponential explosion" when trying to upload 2 line CSV

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2277]
* Specific code commit: d38546b093d59fa53adc4fdc048e54f9c88d1e4f 
* Version of the web browser and OS: mac os
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): dev for chuck and scott

### Steps to reproduce
Please list all the actions and the input data used:

1. Try to import this CSV:
```
ID,Download_Url,Species
1,http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneHuvecCtcfStdAlnRep3.bam,HomoSapiens
``` 

### Observed behavior

* In the UI: "Import of this data set failed. Please ensure that the structure of your metadata file matches that of the example metadata file."
* In the console:
```
TypeError at /data_set_manager/import/metadata-table-form/
RuntimeError('Exponential explosion! Creation of 2 annotated nodes for 1 nodes of type Raw Data File is stopped!',) is not JSON serializable
```
* In the log:
```
2017-10-25 14:45:02 INFO     data_set_manager.single_file_column_parser:183 run() - trying to add pre-isa archive file bam-test-one-liner.csv
2017-10-25 14:45:02 INFO     file_store.tasks:45 create() - Creating FileStoreItem using source 'bam-test-one-liner.csv'
2017-10-25 14:45:02 INFO     file_store.models:375 set_filetype() - File type is set to 'csv'
2017-10-25 14:45:02 INFO     file_store.tasks:54 create() - FileStoreItem created with UUID 1deecb7b-9b7b-4c31-b606-4bf040cf4aae
2017-10-25 14:45:02 DEBUG    file_store.tasks:69 import_file() - Importing FileStoreItem with UUID '1deecb7b-9b7b-4c31-b606-4bf040cf4aae'
2017-10-25 14:45:02 ERROR    file_store.tasks:145 import_file() - Could not open URL 'bam-test-one-liner.csv': 'Invalid URL 'bam-test-one-liner.csv': No schema supplied. Perhaps you meant 
http://bam-test-one-liner.csv?'
2017-10-25 14:45:02 DEBUG    data_set_manager.single_file_column_parser:194 run() - Parsing with file column 1 and auxiliary file column None
2017-10-25 14:45:02 INFO     file_store.tasks:45 create() - Creating FileStoreItem using source 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroad
HistoneHuvecCtcfStdAlnRep3.bam'
2017-10-25 14:45:02 INFO     file_store.models:375 set_filetype() - File type is set to 'bam'
2017-10-25 14:45:02 INFO     file_store.tasks:54 create() - FileStoreItem created with UUID 49489df6-9eb8-4ab9-97ba-1c34d4ff06bf
2017-10-25 14:45:02 DEBUG    file_server:449 _add_bam() - TDF file UUID was not provided
2017-10-25 14:45:02 INFO     file_server:459 _add_bam() - BAMItem created
2017-10-25 14:45:02 ERROR    data_set_manager.utils:470 update_annotated_nodes() - Exponential explosion! Creation of 2 annotated nodes for 1 nodes of type Raw Data File is stopped!
2017-10-25 14:45:02 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /data_set_manager/import/metadata-table-form/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/vagrant/refinery/data_set_manager/views.py", line 554, in post
    json.dumps({'error': error_msg}), 'application/json'
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: RuntimeError('Exponential explosion! Creation of 2 annotated nodes for 1 nodes of type Raw Data File is stopped!',) is not JSON serializable
Internal Server Error: /data_set_manager/import/metadata-table-form/
```

**Comment by scottx611x** [comment]
The RuntimeError should also be caught in `data_set_manager/views.py` and it's `message` should be returned by the view with a `400` response.
