### ISSUE TITLE
Handle RuntimeError produced by search_solr()

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2284]
* Specific code commit: v1.6.0
* Version of the web browser and OS: N/A
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
Unknown (error report received by email)

### Observed behavior
```
Internal Server Error: /api/v2/files/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 56, in get
    solr_response = _get_solr(request.query_params, request.user.id)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 74, in _get_solr
    return search_solr(solr_params, 'data_set_manager')
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 839, in search_solr
    'Expected Solr JSON, not: {}'.format(full_response.content)
RuntimeError: Expected Solr JSON, not:

Request repr():
<WSGIRequest
path:/api/v2/files/,
GET:<QueryDict: {u'sort': [u''], u'fq': [u''], u'limit': [u'100']}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1146552338.1499284228',
'_gat': '1',
'_gid': 'GA1.2.675498884.1509037254',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/plain, */*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,pl;q=0.6,fr;q=0.4',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'sessionid=<redacted>; _gat=1; csrftoken=<redacted>; _ga=GA1.2.1146552338.1499284228; _gid=GA1.2.675498884.1509037254',
'HTTP_DNT': '1',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/files/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
'HTTP_X_CSRFTOKEN': <redacted>,
'HTTP_X_FORWARDED_FOR': '134.174.140.132',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/api/v2/files/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/api/v2/files/',
'QUERY_STRING': 'fq=&limit=100&sort=',
'REMOTE_ADDR': '172.31.62.9',
'REMOTE_PORT': '26868',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/api/v2/files/?fq=&limit=100&sort=',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/api/v2/files/',
'SCRIPT_URL': '/api/v2/files/',
'SERVER_ADDR': '172.31.53.83',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1509128438137315',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7fc9163786b0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7fc91649b120>,
'wsgi.input': <mod_wsgi.Input object at 0x7fc915f861b0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
Exception should be handled.

**Comment by hackdna** [comment]
Still occurs in v1.6.5:
```
Internal Server Error: /files_download
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 28, in user_files_csv
    solr_response = _get_solr(request.GET, request.user.id)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 75, in _get_solr
    return search_solr(solr_params, 'data_set_manager')
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 857, in search_solr
    'Expected Solr JSON, not: {}'.format(full_response.content)
RuntimeError: Expected Solr JSON, not:

Request repr():
<WSGIRequest
path:/files_download,
GET:<QueryDict: {u'sort': [u''], u'fq': [u'']}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.45385885.1525441664',
'_gat_gtag_UA_68942400_4': '1',
'_gid': 'GA1.2.2134678910.1533233589',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.45385885.1525441664; csrftoken=<redacted>; sessionid=<redacted>; _gid=GA1.2.2134678910.1533233589; _gat_gtag_UA_68942400_4=1',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/files/',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '134.174.140.198',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/files_download',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/files_download',
'QUERY_STRING': 'fq=&sort=',
'REMOTE_ADDR': '172.30.0.167',
'REMOTE_PORT': '6118',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/files_download?fq=&sort=',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/files_download',
'SCRIPT_URL': '/files_download',
'SERVER_ADDR': '172.30.0.216',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1533233612801485',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f2afec7ab70>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2afec940a8>,
'wsgi.input': <mod_wsgi.Input object at 0x7f2afec7a770>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```
