### ISSUE TITLE
"./manage.py process_default_table" broken / never worked?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2296]
* Specific code commit: 1301d7a3fbfbd0a612112f2f36b3dddd8db0da67
* Environment where the error occurred: local, inside vagrant

### Steps to reproduce
Please list all the actions and the input data used:

```
$ ./manage.py process_default_table --username guest --title foo --file_name foo.txt
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/vagrant/refinery/data_set_manager/management/commands/process_default_table.py", line 73, in handle
    parser = SingleFileColumnParser()
TypeError: __init__() takes at least 4 arguments (1 given)
```
... which makes sense:
```
class SingleFileColumnParser:
    ...
    def __init__(
        self,
        metadata_file,
        file_source_translator,
        source_column_index,
        ...
    ):
```
but in process_default_table.py:
```
parser = SingleFileColumnParser()
```

### Expected behavior
Easiest just to get rid of the script: How important is it? If we do keep it, add a test.

**Comment by hackdna** [comment]
What does this management command do actually?

**Comment by mccalluc** [comment]
Nothing right now, because of the error. I believe the goal was to allow CSVs to be imported from the command line.

**Comment by hackdna** [comment]
I vote to delete. This code has not been touched in years and it appears to have been superseded by [process_metadata_table command](https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/data_set_manager/management/commands/process_metadata_table.py).
