### ISSUE TITLE
TypeError when adding a FileStoreItem using Django admin site

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2380]
* Specific code commit: 47880d5
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Vagrant and AWS

### Steps to reproduce
1. Navigate to `/admin/file_store/filestoreitem/add/`
1. Fill out the required fields (Source and Filetype) and click "Save"

### Observed behavior
HTTP 500 server error in web browser. Refinery log shows:
```
2017-11-15 17:02:05 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /admin/file_store/filestoreitem/add/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1407, in changeform_view
    self.log_addition(request, new_object)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 776, in log_addition
    object_repr=force_text(object),
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/encoding.py", line 85, in force_text
    s = six.text_type(s)
  File "/vagrant/refinery/file_store/models.py", line 261, in __unicode__
    return self.uuid + ' - ' + self.datafile.name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[15/Nov/2017 17:02:05] "POST /admin/file_store/filestoreitem/add/ HTTP/1.1" 500 172419
```

### Expected behavior
FileStoreItem added with no error.

**Comment by scottx611x** [comment]
@hackdna What is the use case for adding FileStoreItems from the admin ui?

**Comment by hackdna** [comment]
If an operation in the admin site crashes the application then it's a bug.

**Comment by scottx611x** [comment]
@hackdna Okay, I was just asking if there is an actual necessity for performing this operation through the admin ui? Maybe we could just disable this functionality for `FIleStoreItems` if there is no need to add them from the admin ui.

**Comment by hackdna** [comment]
If an operation in the admin site causes a server error that means there's something very likely to be wrong in the application logic. Disabling the admin site functionality is kicking the can down the road.
