### ISSUE TITLE
Solr connection timeout error during data set import

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2394]
* Specific code commit: v1.6.1
* Version of the web browser and OS: Chrome 62 on OS X 10.12.6
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
1. Launch a new stack.
1. Import a [data set](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt) and upload all its data files.

### Observed behavior
* Data set import error in the web browser (console shows HTTP 500 error) but this does not always occur.
* One or more timeout errors in the server log:
```
[Tue Nov 28 12:04:36.734394 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:36 INFO     data_set_manager.utils:491 update_annotated_nodes() - Created 8 annotated nodes from 16 nodes in 0.255532979965 msec
[Tue Nov 28 12:04:36.738471 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:36 INFO     data_set_manager.utils:599 _index_annotated_nodes() - 4 nodes for indexing
[Tue Nov 28 12:04:36.753585 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:36 WARNING  data_set_manager.search_indexes:83 prepare() - Couldn't fetch DataSet for Investigation 68c7a7b8-a3e8-4b82-ac46-e94e794f8151: list index out of range
[Tue Nov 28 12:04:36.761475 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:36 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:04:36.762420 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:36 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.00 seconds.
[Tue Nov 28 12:04:36.762657 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:36 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:04:46.664499 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:46 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do' in 9.902 seconds.
[Tue Nov 28 12:04:46.691030 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:46 WARNING  data_set_manager.search_indexes:83 prepare() - Couldn't fetch DataSet for Investigation 68c7a7b8-a3e8-4b82-ac46-e94e794f8151: list index out of range
[Tue Nov 28 12:04:46.710214 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:46 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:04:46.711208 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:46 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.00 seconds.
[Tue Nov 28 12:04:46.711345 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:46 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:04:48.253150 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:48 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do' in 1.542 seconds.
[Tue Nov 28 12:04:48.270938 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:48 WARNING  data_set_manager.search_indexes:83 prepare() - Couldn't fetch DataSet for Investigation 68c7a7b8-a3e8-4b82-ac46-e94e794f8151: list index out of range
[Tue Nov 28 12:04:48.308669 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:48 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:04:48.334290 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:48 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.03 seconds.
[Tue Nov 28 12:04:48.334514 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:48 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:04:51.729366 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:51 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do' in 3.395 seconds.
[Tue Nov 28 12:04:51.738806 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:51 WARNING  data_set_manager.search_indexes:83 prepare() - Couldn't fetch DataSet for Investigation 68c7a7b8-a3e8-4b82-ac46-e94e794f8151: list index out of range
[Tue Nov 28 12:04:51.745748 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:51 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:04:51.746751 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:51 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.00 seconds.
[Tue Nov 28 12:04:51.746966 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:04:51 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:05:01.828862 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:01 ERROR    pysolr:311 _send_request() - Connection to server 'http://localhost:8983/solr/data_set_manager/update/?commit=true' timed out: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
[Tue Nov 28 12:05:01.828892 2017] [:error] [pid 30074:tid 140456903460608] Traceback (most recent call last):
[Tue Nov 28 12:05:01.828897 2017] [:error] [pid 30074:tid 140456903460608]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/pysolr.py", line 308, in _send_request
[Tue Nov 28 12:05:01.828900 2017] [:error] [pid 30074:tid 140456903460608]     timeout=self.timeout)
[Tue Nov 28 12:05:01.828904 2017] [:error] [pid 30074:tid 140456903460608]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
[Tue Nov 28 12:05:01.828907 2017] [:error] [pid 30074:tid 140456903460608]     return self.request('POST', url, data=data, json=json, **kwargs)
[Tue Nov 28 12:05:01.828911 2017] [:error] [pid 30074:tid 140456903460608]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
[Tue Nov 28 12:05:01.828914 2017] [:error] [pid 30074:tid 140456903460608]     resp = self.send(prep, **send_kwargs)
[Tue Nov 28 12:05:01.828917 2017] [:error] [pid 30074:tid 140456903460608]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
[Tue Nov 28 12:05:01.828921 2017] [:error] [pid 30074:tid 140456903460608]     r = adapter.send(request, **kwargs)
[Tue Nov 28 12:05:01.828924 2017] [:error] [pid 30074:tid 140456903460608]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
[Tue Nov 28 12:05:01.828927 2017] [:error] [pid 30074:tid 140456903460608]     raise ReadTimeout(e, request=request)
[Tue Nov 28 12:05:01.828930 2017] [:error] [pid 30074:tid 140456903460608] ReadTimeout: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
[Tue Nov 28 12:05:01.829192 2017] [:error] [pid 30074:tid 140456903460608] Failed to add documents to Solr: Connection to server 'http://localhost:8983/solr/data_set_manager/update/?commit=true' timed out: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
[Tue Nov 28 12:05:01.829246 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:01 ERROR    haystack:80 update() - Failed to add documents to Solr: Connection to server 'http://localhost:8983/solr/data_set_manager/update/?commit=true' timed out: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
[Tue Nov 28 12:05:01.829409 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:01 INFO     data_set_manager.utils:608 _index_annotated_nodes() - 4 nodes indexed in 25.0907149315
[Tue Nov 28 12:05:31.865192 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 INFO     data_set_manager.tasks:301 create_dataset() - create_dataset: title = hg19-metadata-local, identifer = None, dataset_name = 'hg19-metadata-local'
[Tue Nov 28 12:05:31.887626 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 INFO     core.utils:51 update_data_set_index() - Updated data set (uuid: b5a773a0-ca19-475e-afd6-0d70d7943876) index
[Tue Nov 28 12:05:31.887843 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 INFO     core.search_indexes:138 prepare() - Start preparing 'hg19-metadata-local' for indexing
[Tue Nov 28 12:05:31.896545 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 ERROR    core.search_indexes:54 prepare_description() - Could not fetch Investigation for DataSet with UUID: b5a773a0-ca19-475e-afd6-0d70d7943876 'NoneType' object has no attribute 'get_description'
[Tue Nov 28 12:05:31.975702 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 INFO     core.search_indexes:172 prepare() - Successfully prepared 'hg19-metadata-local' for indexing
[Tue Nov 28 12:05:31.975956 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:05:31.976662 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.00 seconds.
[Tue Nov 28 12:05:31.976862 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:31 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:05:33.540829 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:33 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<add><do' in 1.564 seconds.
[Tue Nov 28 12:05:33.799273 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:33 INFO     data_set_manager.tasks:322 create_dataset() - create_dataset: Created data set 'hg19-metadata-local'
[Tue Nov 28 12:05:33.887381 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:33 INFO     core.utils:51 update_data_set_index() - Updated data set (uuid: b5a773a0-ca19-475e-afd6-0d70d7943876) index
[Tue Nov 28 12:05:33.887525 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:33 INFO     core.search_indexes:138 prepare() - Start preparing 'hg19-metadata-local' for indexing
[Tue Nov 28 12:05:34.142894 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:34 INFO     core.search_indexes:172 prepare() - Successfully prepared 'hg19-metadata-local' for indexing
[Tue Nov 28 12:05:34.144596 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:34 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:05:34.145530 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:34 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.00 seconds.
[Tue Nov 28 12:05:34.155954 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:34 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:05:35.740976 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<add><do' in 1.585 seconds.
[Tue Nov 28 12:05:35.745436 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 INFO     core.utils:51 update_data_set_index() - Updated data set (uuid: b5a773a0-ca19-475e-afd6-0d70d7943876) index
[Tue Nov 28 12:05:35.745631 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 INFO     core.search_indexes:138 prepare() - Start preparing 'hg19-metadata-local' for indexing
[Tue Nov 28 12:05:35.926229 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 INFO     core.search_indexes:172 prepare() - Successfully prepared 'hg19-metadata-local' for indexing
[Tue Nov 28 12:05:35.938723 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 DEBUG    pysolr:797 add() - Starting to build add request...
[Tue Nov 28 12:05:35.939666 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 DEBUG    pysolr:812 add() - Built add request of 1 docs in 0.00 seconds.
[Tue Nov 28 12:05:35.940107 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:35 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<add><do'...
[Tue Nov 28 12:05:37.521100 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:37 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<add><do' in 1.581 seconds.
[Tue Nov 28 12:05:37.521285 2017] [:error] [pid 30074:tid 140456903460608] 2017-11-28 12:05:37 INFO     core.utils:70 add_data_set_to_neo4j() - Add dataset (uuid: b5a773a0-ca19-475e-afd6-0d70d7943876) to Neo4J and give read access to user (id: 5)
```

### Expected behavior
Data set is imported correctly. No errors in the log.

### Notes
This type of error also occurs when deleting an analysis:
```
[Mon Dec 11 16:42:59.392940 2017] [:error] [pid 30198:tid 140267737696000] 2017-12-11 16:42:59 INFO     core.models:1317 galaxy_cleanup() - Purging galaxy of libraries, histories, and workflows related to the execution of Analysis with UUID: 1b5787a5-4c4c-46df-8ba6-ed88dc016f58
[Mon Dec 11 16:42:59.559550 2017] [:error] [pid 30198:tid 140267737696000] 2017-12-11 16:42:59 ERROR    core.models:1330 galaxy_cleanup() - Could not properly fetch Tool: WorkflowTool matching query does not exist.
[Mon Dec 11 16:42:59.565125 2017] [:error] [pid 30198:tid 140267737696000] 2017-12-11 16:42:59 DEBUG    pysolr:291 _send_request() - Starting request to 'http://localhost:8983/solr/data_set_manager/update/?commit=true' (post) with body 'u'<optimiz'...
[Mon Dec 11 16:43:09.600124 2017] [:error] [pid 30198:tid 140267737696000] 2017-12-11 16:43:09 ERROR    pysolr:311 _send_request() - Connection to server 'http://localhost:8983/solr/data_set_manager/update/?commit=true' timed out: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
[Mon Dec 11 16:43:09.600150 2017] [:error] [pid 30198:tid 140267737696000] Traceback (most recent call last):
[Mon Dec 11 16:43:09.600156 2017] [:error] [pid 30198:tid 140267737696000]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/pysolr.py", line 308, in _send_request
[Mon Dec 11 16:43:09.600160 2017] [:error] [pid 30198:tid 140267737696000]     timeout=self.timeout)
[Mon Dec 11 16:43:09.600169 2017] [:error] [pid 30198:tid 140267737696000]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
[Mon Dec 11 16:43:09.600173 2017] [:error] [pid 30198:tid 140267737696000]     return self.request('POST', url, data=data, json=json, **kwargs)
[Mon Dec 11 16:43:09.600176 2017] [:error] [pid 30198:tid 140267737696000]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
[Mon Dec 11 16:43:09.600179 2017] [:error] [pid 30198:tid 140267737696000]     resp = self.send(prep, **send_kwargs)
[Mon Dec 11 16:43:09.600182 2017] [:error] [pid 30198:tid 140267737696000]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
[Mon Dec 11 16:43:09.600185 2017] [:error] [pid 30198:tid 140267737696000]     r = adapter.send(request, **kwargs)
[Mon Dec 11 16:43:09.600188 2017] [:error] [pid 30198:tid 140267737696000]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
[Mon Dec 11 16:43:09.600191 2017] [:error] [pid 30198:tid 140267737696000]     raise ReadTimeout(e, request=request)
[Mon Dec 11 16:43:09.600194 2017] [:error] [pid 30198:tid 140267737696000] ReadTimeout: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
[Mon Dec 11 16:43:09.600320 2017] [:error] [pid 30198:tid 140267737696000] 2017-12-11 16:43:09 ERROR    core.models:1249 optimize_solr_index() - Could not optimize Solr's index: Connection to server 'http://localhost:8983/solr/data_set_manager/update/?commit=true' timed out: HTTPConnectionPool(host='localhost', port=8983): Read timed out. (read timeout=10)
```

**Comment by hackdna** [comment]
Still an issue in v1.6.7
