### ISSUE TITLE
Assertion error in test_analysis_deletion

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2408]
* Specific code commit: e2bb3a6a
* Version of the web browser and OS: N/A
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Vagrant VM

### Steps to reproduce
Run:
```shell
manage.py test selenium_testing.tests.UiDeletionTestCase.test_analysis_deletion
```

### Observed behavior
Test run output:
```
2017-12-05 17:00:52 INFO     core.models:1331 galaxy_cleanup() - Purging galaxy of libraries, histories, and workflows related to the execution of Analysis with UUID: 96a8c5f5-989d-4f0c-98f9-799f28ea388c
2017-12-05 17:00:52 ERROR    django.request:231 handle_uncaught_exception() - Internal Server Error: /api/v2/analyses/96a8c5f5-989d-4f0c-98f9-799f28ea388c/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/vagrant/refinery/core/views.py", line 913, in delete
    analysis_deleted = Analysis.objects.get(uuid=uuid).delete()
  File "/vagrant/refinery/core/models.py", line 1196, in delete
    self.cancel()
  File "/vagrant/refinery/core/models.py", line 1359, in cancel
    self.galaxy_cleanup()
  File "/vagrant/refinery/core/models.py", line 1333, in galaxy_cleanup
    self.galaxy_instance().delete_library(self.library_id, self.name)
  File "/vagrant/refinery/galaxy_connector/models.py", line 72, in delete_library
    self.galaxy_connection().libraries.delete_library(library_id)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxy/libraries/__init__.py", line 54, in delete_library
    return self._delete(id=library_id)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 187, in _delete
    r = self.gi.make_delete_request(url, payload=payload, params=params)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 160, in make_delete_request
    r = requests.delete(url, verify=self.verify, data=payload, params=params)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/api.py", line 147, in delete
    return request('delete', url, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/requests/models.py", line 365, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http:///api/libraries': No host supplied
...
FAIL: test_analysis_deletion (selenium_testing.tests.UiDeletionTestCase)
Delete some analyses and make sure the UI updates properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/refinery/selenium_testing/tests.py", line 64, in test_analysis_deletion
    delete_from_ui(self.browser, "analysis", total_analyses)
  File "/vagrant/refinery/selenium_testing/utils.py", line 201, in delete_from_ui
    "{} {}".format(total_objects, object_name))
  File "/vagrant/refinery/selenium_testing/utils.py", line 96, in assert_text_within_id
    selenium.find_element_by_id(search_id).text
AssertionError: "1 analysis" not in total-analyses:
2 analyses
```

### Expected behavior
No test errors or failures.

**Comment by hackdna** [comment]
Git bisect indicates that the problem was introduced in 87cd176b. @scottx611x could you have a look since this is your code?

**Comment by scottx611x** [comment]
@hackdna is this failing on travis too or just in your local enviornment?

**Comment by hackdna** [comment]
No failure on Travis. Also, no failure in Vagrant before 87cd176b.
