### ISSUE TITLE
Unable to create stack with currently pinned deployment/requirements.txt

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2477]
* Specific code commit: `8b2625abbe58f0bd0807aec82789c10a4c1152b6`
* Version of the web browser and OS: `macOS 10.12`

### Steps to reproduce
Please list all the actions and the input data used:

1.  Get to a point where you can run `python stack.py create` Follow the steps [here](https://github.com/refinery-platform/refinery-platform/wiki/AWS-deployment)

### Observed behavior
```
Traceback (most recent call last):
  File "stack.py", line 565, in <module>
    main()
  File "stack.py", line 43, in main
    template = make_template(config, config_yaml)
  File "stack.py", line 80, in make_template
    config_uri = save_s3_config(config)
  File "/Users/scott/PyCharmProjects/refinery-platform/deployment/utils.py", line 129, in save_s3_config
    s3 = boto3.resource('s3')
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/__init__.py", line 92, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/botocore/session.py", line 796, in create_client
    client_config=config, api_version=api_version)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/botocore/client.py", line 59, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/botocore/client.py", line 76, in _create_client_class
    base_classes=bases)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/Users/scott/.virtualenvs/refinery-deployment/lib/python2.7/site-packages/boto3/s3/transfer.py", line 129, in <module>
    from s3transfer.manager import TransferConfig as S3TransferConfig
ImportError: No module named manager
```
### Expected behavior
* For this command to work

### General Notes:
* Upgrading to `awscli==1.14.26` resolves this

**Comment by scottx611x** [comment]
Closed by #2478
