### ISSUE TITLE
WebDriverException in test_HiGlass

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2538]
* Specific code commit: bea7f6d
* Version of the web browser and OS: N/A
* Environment where the error occurred: Travis CI

### Steps to reproduce
Start a Travis CI build

### Observed behavior
[Travis CI build](https://travis-ci.org/refinery-platform/refinery-platform/builds/333307038) fails with:
```
ERROR: test_HiGlass (tool_manager.tests.VisualizationToolLaunchTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/tool_manager/tests.py", line 3442, in setUp
    SeleniumTestBaseGeneric.setUp(self)
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/selenium_testing/utils.py", line 25, in setUp
    self.browser = webdriver.Firefox()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    keep_alive=True)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: connection refused
```

### Expected behavior
No error

### Notes
May be related to #2238

**Comment by scottx611x** [comment]
This test doesn't exist anymore (nor do the other selenium-based tests)
