### ISSUE TITLE
Odd (Spam) User accounts on the Beta Site

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2543]
See: 
![screen shot 2018-01-29 at 10 43 03 am](https://user-images.githubusercontent.com/5629547/35519072-3d4be06c-04e1-11e8-8487-3678f512a0a3.png)

We should delete these accounts and be more wary of what user accounts we activate

Potentially related to: https://github.com/refinery-platform/refinery-platform/issues/2535

**Comment by scottx611x** [comment]
Looking at this closer I see that none of these odd looking accounts that I've found are activated. 
I've also gotten a 500 error when trying to delete a few of them `LorenTox` in particular.

```
Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1511, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1282, in response_action
    response = func(self, request, queryset)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 153, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 211, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 194, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 196, in _nested
    ret = [format_callback(obj)]
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 126, in format_callback
    force_text(obj))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/encoding.py", line 85, in force_text
    s = six.text_type(s)
  File "/srv/refinery-platform/refinery/core/models.py", line 97, in __unicode__
    str(self.affiliation) + "): " +
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0443' in position 15: ordinal not in range(128)
```

Trying to view the associated `User Profile` in the admin ui led me to this again https://github.com/refinery-platform/refinery-platform/issues/2165

**Comment by hackdna** [comment]
It's a common use case, so there should be an option of deleting these accounts instead of activating them.

**Comment by scottx611x** [comment]
I've since removed these accounts.
Closing in favor of https://github.com/refinery-platform/refinery-platform/issues/2575
