### ISSUE TITLE
UnicodeEncodeError in UserProfile

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2557]
* Specific code commit: v1.6.2
* Version of the web browser and OS: unknown
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
```
Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1511, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1282, in response_action
    response = func(self, request, queryset)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 153, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 211, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 194, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 196, in _nested
    ret = [format_callback(obj)]
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 126, in format_callback
    force_text(obj))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/encoding.py", line 85, in force_text
    s = six.text_type(s)
  File "/srv/refinery-platform/refinery/core/models.py", line 97, in __unicode__
    str(self.affiliation) + "): " +
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0443' in position 15: ordinal not in range(128)

Request repr():
<WSGIRequest
path:/admin/auth/user/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'action': [u'delete_selected'], u'select_across': [u'0'], u'csrfmiddlewaretoken': <redacted>, u'_selected_action': [u'51', u'44', u'43', u'56', u'46', u'42', u'36', u'41', u'35'], u'index': [u'0']}>,
COOKIES:{'_ga': 'GA1.2.1146552338.1499284228',
'_gid': 'GA1.2.1640854303.1517425791',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTENT_LENGTH': '279',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9,pl;q=0.8,fr;q=0.7',
'HTTP_CACHE_CONTROL': 'max-age=0',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1146552338.1499284228; _gid=GA1.2.1640854303.1517425791; csrftoken=<redacted>; sessionid=<redacted>,
'HTTP_DNT': '1',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_ORIGIN': 'https://beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/admin/auth/user/',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '134.174.140.132',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/admin/auth/user/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/admin/auth/user/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.3.144',
'REMOTE_PORT': '13639',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/admin/auth/user/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/admin/auth/user/',
'SCRIPT_URL': '/admin/auth/user/',
'SERVER_ADDR': '172.31.10.66',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1517433536524938',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f010a8cddb0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f00f3a45198>,
'wsgi.input': <mod_wsgi.Input object at 0x7f010a93eab0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No error

### Notes
It appears that UserProfile is not capable of handling [Unicode characters](https://docs.python.org/2/howto/unicode.html)
See also: #2543

**Comment by jkmarx** [comment]
Same error as #2803. Resolved by pull request #2863
