### ISSUE TITLE
Potentially Flaky Unit Tests 

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2610]
```
FAIL: test_dataset_deletion (selenium_testing.tests.UiDeletionTestCase)
Delete some datasets and make sure the UI updates properly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/selenium_testing/tests.py", line 47, in test_dataset_deletion
    "{} data sets".format(total_datasets)
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/selenium_testing/utils.py", line 96, in assert_text_within_id
    selenium.find_element_by_id(search_id).text
AssertionError: "2 data sets" not in total-datasets: 
0 data sets
======================================================================
FAIL: test_that_dataset_404s_are_handled (selenium_testing.tests.UiDeletionTestCase)
Test use case where DataSet objects are deleted (for example by an
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/selenium_testing/tests.py", line 118, in test_that_dataset_404s_are_handled
    "{} data sets".format(1))
  File "/home/travis/build/refinery-platform/refinery-platform/refinery/selenium_testing/utils.py", line 96, in assert_text_within_id
    selenium.find_element_by_id(search_id).text
AssertionError: "1 data sets" not in total-datasets: 
0 data sets
```
All tests pass locally.

See also #1996, #2348, #2538, #2238

**Comment by jkmarx** [comment]
Remove these tests.

**Comment by jkmarx** [comment]
- [ ] JM projects for integration test
