### ISSUE TITLE
RuntimeError in files API

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2623]
* Specific code commit: v1.6.2
* Version of the web browser and OS: unknown
* Environment where the error occurred: AWS

### Steps to reproduce
@gmnelson: "I went to the User Files browser while logged in as admin (so lots of files)"

### Observed behavior
```
Internal Server Error: /api/v2/files/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 56, in get
    solr_response = _get_solr(request.query_params, request.user.id)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 74, in _get_solr
    return search_solr(solr_params, 'data_set_manager')
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 854, in search_solr
    'Expected Solr JSON, not: {}'.format(full_response.content)
RuntimeError: Expected Solr JSON, not:

Request repr():
<WSGIRequest
path:/api/v2/files/,
GET:<QueryDict: {u'sort': [u''], u'fq': [u''], u'limit': [u'100']}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1639004996.1517425836',
'_gat_gtag_UA_68942400_4': '1',
'_gid': 'GA1.2.196350427.1519054822',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/plain, */*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1639004996.1517425836; _gid=GA1.2.196350427.1519054822; csrftoken=<redacted>; sessionid=<redacted>; _gat_gtag_UA_68942400_4=1',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/files/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36',
'HTTP_X_CSRFTOKEN': 'E4tuLKTD4Qb20dczzQEvtoj6QVmFcAV5',
'HTTP_X_FORWARDED_FOR': '134.174.140.132',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/api/v2/files/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/api/v2/files/',
'QUERY_STRING': 'fq=&limit=100&sort=',
'REMOTE_ADDR': '172.31.10.35',
'REMOTE_PORT': '58836',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/api/v2/files/?fq=&limit=100&sort=',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/api/v2/files/',
'SCRIPT_URL': '/api/v2/files/',
'SERVER_ADDR': '172.31.10.66',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1519414196923058',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f0109a86730>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f010a154e40>,
'wsgi.input': <mod_wsgi.Input object at 0x7f0109a86b70>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No error

**Comment by hackdna** [comment]
See also #2284

**Comment by hackdna** [comment]
Still occurs in v1.6.5

**Comment by jkmarx** [comment]
Solr's response is a 414. 
I reproduced locally with 200+ datasets. "The HTTP 414 URI Too Long response status code indicates that the URI requested by the client is longer than the server is willing to interpret."

**Comment by jkmarx** [comment]
"The default HTTP header size limit on most webservers and containers (including the Jetty that ships with Solr) is 8192 bytes.... posts is 2MB."  http://lucene.472066.n3.nabble.com/URI-is-too-long-td4254270.html
