### ISSUE TITLE
BII Import: "ISA-Tab import Failure: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2631]
* Specific code commit: c2b604771352702d94901998828ee25027546c63 
* Version of the web browser and OS: FF Mac
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): BII demo deployment

### Steps to reproduce
Please list all the actions and the input data used:

1. `./bii2refinery.py --study_id GSE11138`
2. Upload resulting zip

### Observed behavior
* After a moment, we get this error message: "ISA-Tab import Failure: 'NoneType' object is not iterable"

### Expected behavior
I'm not convinced that the ISA Tab is badly formatted. If it is, there should be a suggestion about how to fix the error.

**Comment by scottx611x** [comment]
Some extra info:
```
[Tue Feb 27 13:24:14.838614 2018] [:error] [pid 1559:tid 140328122304256] 2018-02-27 13:24:14 INFO     file_store.tasks:103 import_file() - File copied from '/data/media/file_store/temp/GSE11138.zip'
[Tue Feb 27 13:24:14.852961 2018] [:error] [pid 1559:tid 140328122304256] 2018-02-27 13:24:14 ERROR    data_set_manager.views:331 post() - ISA-Tab import Failure:  Traceback (most recent call last):
[Tue Feb 27 13:24:14.852973 2018] [:error] [pid 1559:tid 140328122304256]   File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 317, in post
[Tue Feb 27 13:24:14.852988 2018] [:error] [pid 1559:tid 140328122304256]     identity_id=identity_id
[Tue Feb 27 13:24:14.852991 2018] [:error] [pid 1559:tid 140328122304256]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
[Tue Feb 27 13:24:14.852994 2018] [:error] [pid 1559:tid 140328122304256]     return self.run(*args, **kwargs)
[Tue Feb 27 13:24:14.852997 2018] [:error] [pid 1559:tid 140328122304256]   File "/srv/refinery-platform/refinery/data_set_manager/tasks.py", line 396, in parse_isatab
[Tue Feb 27 13:24:14.852999 2018] [:error] [pid 1559:tid 140328122304256]     investigation.uuid, username, public=public
[Tue Feb 27 13:24:14.853002 2018] [:error] [pid 1559:tid 140328122304256]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
[Tue Feb 27 13:24:14.853005 2018] [:error] [pid 1559:tid 140328122304256]     return self.run(*args, **kwargs)
[Tue Feb 27 13:24:14.853007 2018] [:error] [pid 1559:tid 140328122304256]   File "/srv/refinery-platform/refinery/data_set_manager/tasks.py", line 220, in create_dataset
[Tue Feb 27 13:24:14.853009 2018] [:error] [pid 1559:tid 140328122304256]     annotate_nodes(investigation_uuid)
[Tue Feb 27 13:24:14.853012 2018] [:error] [pid 1559:tid 140328122304256]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
[Tue Feb 27 13:24:14.853015 2018] [:error] [pid 1559:tid 140328122304256]     return self.run(*args, **kwargs)
[Tue Feb 27 13:24:14.853017 2018] [:error] [pid 1559:tid 140328122304256]   File "/srv/refinery-platform/refinery/data_set_manager/tasks.py", line 290, in annotate_nodes
[Tue Feb 27 13:24:14.853019 2018] [:error] [pid 1559:tid 140328122304256]     for node_type in node_types:
[Tue Feb 27 13:24:14.853022 2018] [:error] [pid 1559:tid 140328122304256] TypeError: 'NoneType' object is not iterable
[Tue Feb 27 13:24:14.853024 2018] [:error] [pid 1559:tid 140328122304256]
```
