### ISSUE TITLE
Remove related objects when deleting a data set

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2632]
* Specific code commit: 64ef52b
* Version of the web browser and OS: Chrome 64 on OS X 10.12.6
* Environment where the error occurred: Vagrant

### Steps to reproduce
1. Import a [data set](http://data.cloud.refinery-platform.org.s3.amazonaws.com/data/sample-data/human-chipseq/hg19-metadata-local.txt)
1. Navigate to the launch pad and delete this data set

### Observed behavior
The following instances remain in the database:
* 4 FileStoreItem
* 16 Node
* 1 Investigation
* 1 Study
* 1 Assay
* 2 NodeCollection

Also, It is impossible to delete some of the remaining objects manually (e.g., Investigation)

### Expected behavior
* All objects related to the data set should be deleted
* It should be possible to delete remaining objects manually

### Notes
Refinery log:
```
2018-02-27 17:17:45 DEBUG    core.models:741 get_isa_archive() - Couldn't fetch FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:558 delete() - DataSet has no isa_archive to delete: 'NoneType' object has no attribute 'delete'
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.models:2185 _nodecollection_delete() - Could not delete FileStoreItem:FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:572 delete() - Couldn't delete NodeCollection: Cannot query "None: hg19-metadata-local: 52": Must be "Study" instance.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 ERROR    core.models:820 get_file_store_items() - Error while fetching FileStoreItem: FileStoreItem matching query does not exist.
2018-02-27 17:17:45 DEBUG    core.utils:374 delete_data_set_index() - Deleted data set (uuid: 0acdf4c4-4e85-43b6-bb8f-64a3f2599fe0) index
2018-02-27 17:17:45 INFO     pysolr:325 _send_request() - Finished 'http://localhost:8983/solr/core/update/?commit=true' (post) with body 'u'<delete>' in 0.160 seconds.
2018-02-27 17:17:45 DEBUG    core.utils:390 delete_data_set_neo4j() - Deleted data set (uuid: 0acdf4c4-4e85-43b6-bb8f-64a3f2599fe0) in Neo4J
```

Also, when trying to delete some of the remaining objects manually:
```
2018-02-27 17:33:36 ERROR    django.request:256 handle_uncaught_exception() - Internal Server Error: /admin/data_set_manager/investigation/52/delete/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1718, in delete_view
    self.delete_model(request, obj)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1086, in delete_model
    obj.delete()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/base.py", line 896, in delete
    collector.delete()
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 287, in delete
    sender=model, instance=obj, using=self.using
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/vagrant/refinery/core/models.py", line 2180, in _nodecollection_delete
    nodes = Node.objects.filter(study=instance)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1179, in build_filter
    self.check_related_objects(field, value, opts)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1074, in check_related_objects
    self.check_query_object_type(value, opts)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1058, in check_query_object_type
    (value, opts.object_name))
ValueError: Cannot query "None: hg19-metadata-local: 52": Must be "Study" instance.
[27/Feb/2018 17:33:36] "POST /admin/data_set_manager/investigation/52/delete/ HTTP/1.1" 500 224870
```

**Comment by scottx611x** [comment]
Related to: #1614
