### ISSUE TITLE
Internal Server Error from /solr/core/select

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2639]
* Specific code commit: c2b604771352702d94901998828ee25027546c63
* Version of the web browser and OS: Any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
1. Search for any term in the Solr search bar above the DataSet listing on the dashboard
2. Notice the change in url: `<site>/#/?q=youmadeaquery` 
   - **NOTE: The results of the search don't seem to matter.**
3. Refresh the page

### Observed behavior
```
[Wed Feb 28 15:11:02.721336 2018] [:error] [pid 2596:tid 140631568996096] 2018-02-28 15:11:02 ERROR    django.request:256 handle_uncaught_exception() - Internal Server Error: /solr/core/select/
[Wed Feb 28 15:11:02.721501 2018] [:error] [pid 2596:tid 140631568996096] Traceback (most recent call last):
[Wed Feb 28 15:11:02.721564 2018] [:error] [pid 2596:tid 140631568996096]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
[Wed Feb 28 15:11:02.721620 2018] [:error] [pid 2596:tid 140631568996096]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Feb 28 15:11:02.721710 2018] [:error] [pid 2596:tid 140631568996096]   File "/srv/refinery-platform/refinery/core/views.py", line 551, in solr_core_search
[Wed Feb 28 15:11:02.721767 2018] [:error] [pid 2596:tid 140631568996096]     return JsonResponse(response)
[Wed Feb 28 15:11:02.721819 2018] [:error] [pid 2596:tid 140631568996096]   File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/http/response.py", line 532, in __init__
[Wed Feb 28 15:11:02.721873 2018] [:error] [pid 2596:tid 140631568996096]     raise TypeError('In order to allow non-dict objects to be '
[Wed Feb 28 15:11:02.721925 2018] [:error] [pid 2596:tid 140631568996096] TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False
```
### Expected behavior
* No error. Ability to refresh the page without 500

**Comment by jkmarx** [comment]
I notice this error when removing a different API. https://github.com/refinery-platform/refinery-platform/pull/2665 should resolve it
