### ISSUE TITLE
Import Into Own Space error template

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2681]
* Specific code commit: e859c8eb301a7aeb95222d36629e354d1bc4bb45
* Version of the web browser and OS: SCC Beta Site
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Chrome

### Steps to reproduce
Please list all the actions and the input data used:

1. Select a non-isatab data set you own  (Ref #2518) *Note this method is just a way to produce the error template. I'm assuming there's other ways for the user to get redirected here also.
2. Click import into own space

### Observed behavior
Redirect
<img width="1094" alt="screen shot 2018-03-20 at 7 33 33 pm" src="https://user-images.githubusercontent.com/9956764/37688278-9ef981fa-2c75-11e8-99af-16570302ab84.png">

### Expected behavior
* No error

**Comment by jkmarx** [comment]
- [ ] import into own space showing for data sets I own

**Comment by ngehlenborg** [comment]
Was that public data set uploaded via ISA-Tab?

**Comment by jkmarx** [comment]
@ngehlenborg No. I just confirmed and updated the instructions above.

**Comment by scottx611x** [comment]
Wondering if this is a duplicate of: https://github.com/refinery-platform/refinery-platform/issues/2101 ?

**Comment by hackdna** [comment]
GET request against `/data_set_manager/import/isa-tab-form/` still results in HTTP 500 (d9a3db9):
```
2018-03-21 17:31:02 ERROR    django.request:256 handle_uncaught_exception() - Internal Server Error: /data_set_manager/import/isa-tab-form/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/vagrant/refinery/data_set_manager/views.py", line 175, in get
    context_instance=context)
  File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/vagrant/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader.py", line 137, in render_to_string
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: data_set_manager/isa-tab-import.html
```

**Comment by jkmarx** [comment]
@hackdna please write a separate issue

**Comment by hackdna** [comment]
This is exactly the same error and the root cause (missing template `data_set_manager/isa-tab-import.html`) has not been addressed

![screen shot 2018-03-21 at 18 51 26](https://user-images.githubusercontent.com/452575/37741746-ffba5b72-2d38-11e8-8c15-ddeef8de8dc6.png)

**Comment by jkmarx** [comment]
@hackdna https://github.com/refinery-platform/refinery-platform/issues/2101

**Comment by hackdna** [comment]
#2101 is about rewriting `TakeOwnershipOfPublicDatasetView`:
* to perform a deep copy of the imported data set instead of re-importing the original ISA archive
* to add support for data sets imported from tabular files

This `TemplateDoesNotExist` error is due to a missing template (deleted in b28b996).
