### ISSUE TITLE
Internal Server Error: /assets/images/touchicon.png

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2702]
* Specific code commit: v1.6.2
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
Access log:
```
66.249.90.186 172.31.9.249 - - [27/Mar/2018:20:43:05 +0000] "GET /visualizations/HiGlass-182bcd42-70ee-46ba-bcfc-593a644983e2/assets/images/touchicon.png HTTP/1.1" 500 15544 222790 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
```
Error log:
```
Internal Server Error: /assets/images/touchicon.png
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 79, in _proxy_view
    return view(request, url=url)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 82, in dispatch
    response = super(HttpProxy, self).dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 141, in get
    return self.get_response()
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/httpproxy/views.py", line 166, in get_response
    response = urllib.request.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Request repr():
<WSGIRequest
path:/assets/images/touchicon.png,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_ACCEPT_ENCODING': 'gzip,deflate,br',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_FROM': 'googlebot(at)googlebot.com',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '66.249.90.187',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/assets/images/touchicon.png',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/visualizations/HiGlass-182bcd42-70ee-46ba-bcfc-593a644983e2/assets/images/touchicon.png',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.31.9.249',
'REMOTE_PORT': '7042',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/visualizations/HiGlass-182bcd42-70ee-46ba-bcfc-593a644983e2/assets/images/touchicon.png',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/visualizations/HiGlass-182bcd42-70ee-46ba-bcfc-593a644983e2/assets/images/touchicon.png',
'SCRIPT_URL': '/visualizations/HiGlass-182bcd42-70ee-46ba-bcfc-593a644983e2/assets/images/touchicon.png',
'SERVER_ADDR': '172.31.10.66',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1522183496312576',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f010a464af0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f010a97a468>,
'wsgi.input': <mod_wsgi.Input object at 0x7f010a4648f0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No error

### Notes
See also #2703

**Comment by scottx611x** [comment]
Errors coming from visualizations like this one are now handled now by the newer version of `django-docker-engine==0.0.42` and won't propogate to Refinery.
This can be closed once we've updated.

**Comment by scottx611x** [comment]
Closing. `django-docker-engine==0.0.42.2` with a fix for this is now part of `develop`
