### ISSUE TITLE
User-files filter bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2710]
* Specific code commit: 8f071da33e45f263fc6f6d8f1fd43686a7949a81
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
Beta site

### Steps to reproduce
Please list all the actions and the input data used:

1. Filters in user/files

### Observed behavior
```
Internal Server Error: /api/v2/files/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 57, in get
    solr_response = _get_solr(request.query_params, request.user.id)
  File "/srv/refinery-platform/refinery/user_files_manager/views.py", line 66, in _get_solr
    user_id=user_id)
  File "/srv/refinery-platform/refinery/user_files_manager/utils.py", line 59, in generate_solr_params_for_user
    facets_from_config=True)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 680, in generate_solr_params
    facet_field = insert_facet_field_filter(facet_filter, facet_field)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 746, in insert_facet_field_filter
    ind = facet_field_arr.index(facet)
ValueError: u'organism' is not in list

GET:<QueryDict: {u'sort': [u''], u'limit': [u'100'], u'filter_attribute': [u'{"organism":["Homo%20sapiens","Mus%20musculus"]}']}>,
…
 'QUERY_STRING': 'filter_attribute=%7B%22organism%22:%5B%22Homo%2520sapiens%22,%22Mus%2520musculus%22%5D%7D&limit=100&sort=',
 'REMOTE_ADDR': '172.30.0.226',
 'REMOTE_PORT': '19019',

 'REQUEST_METHOD': 'GET',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/api/v2/files/?filter_attribute=%7B%22organism%22:%5B%22Homo%2520sapiens%22,%22Mus%2520musculus%22%5D%7D&limit=100&sort=',

 'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
 'SCRIPT_NAME': u'',
 'SCRIPT_URI': 'http://beta.stemcellcommons.org/api/v2/files/',
 'SCRIPT_URL': '/api/v2/files/',
 'SERVER_ADDR': '172.30.0.50',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'beta.stemcellcommons.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
 'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.process_group': 'refinery',
 'mod_wsgi.queue_start': '1522890651066341',

 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 4),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f043fcd7d70>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f043dededc8>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f043fcd7e70>,
```
### Expected behavior
No errors

### Notes
See also #2729 and #2931

**Comment by jkmarx** [comment]
Removed insert_facet_filter method in pull request #2950
