### ISSUE TITLE
Handle ValueError in insert_facet_field_filter

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2729]
* Specific code commit: v1.6.3
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
Error log:
```
Internal Server Error: /api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 812, in get
    solr_params = generate_solr_params_for_assay(params, uuid)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 627, in generate_solr_params_for_assay
    return generate_solr_params(params, [assay_uuid], False, exclude_facets)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 695, in generate_solr_params
    facet_field = insert_facet_field_filter(facet_filter, facet_field)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 744, in insert_facet_field_filter
    facet_filter = json.loads(facet_filter)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Request repr():
<WSGIRequest
path:/api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/,
GET:<QueryDict: {u'data_set_uuid': [u'8566395e-a41e-4f49-89c2-bd52444a4707'], u'offset': [u'0'], u'limit': [u'100'], u'filter_attribute': [u'{"REFINERY_ANALYSIS_UUID_160_80_s":TF ChIP-Seq analysis using MACS2: hg19 2016-7-22@2:28:54']}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1354209348.1507481536',
'_gid': 'GA1.2.1215373137.1524486035',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1354209348.1507481536; csrftoken=<redacted>; sessionid=<redacted>; _gid=GA1.2.1215373137.1524486035',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '209.6.122.26',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/',
'QUERY_STRING': 'data_set_uuid=8566395e-a41e-4f49-89c2-bd52444a4707&filter_attribute=%7B%22REFINERY_ANALYSIS_UUID_160_80_s%22:TF%20ChIP-Seq%20analysis%20using%20MACS2:%20hg19%202016-7-22@2:28:54&limit=100&offset=0',
'REMOTE_ADDR': '172.30.0.35',
'REMOTE_PORT': '42972',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/?data_set_uuid=8566395e-a41e-4f49-89c2-bd52444a4707&filter_attribute=%7B%22REFINERY_ANALYSIS_UUID_160_80_s%22:TF%20ChIP-Seq%20analysis%20using%20MACS2:%20hg19%202016-7-22@2:28:54&limit=100&offset=0',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/',
'SCRIPT_URL': '/api/v2/assays/9cce34a3-fc84-4b6e-8a2c-a0448f267126/files/',
'SERVER_ADDR': '172.30.0.50',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1524611205549539',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f0456493470>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f04565c2120>,
'wsgi.input': <mod_wsgi.Input object at 0x7f0456493230>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No error

### Notes
See also #2710 and #2931

**Comment by jkmarx** [comment]
Ref #2710 Related?
