### ISSUE TITLE
Superuser creation failure when stack doesn't reference backups

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2738]
* Specific code commit: 120559a8cb746573301f958446b634838e60e732
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
Please list all the actions and the input data used:

1.  Bring up a stack (terraform and cloudformation) that doesn't specify `RDS_SNAPSHOT` or `DATA_SNAPSHOT`
2. Watch `/var/log/cloud-init-output.log`

### Observed behavior
```
Notice: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns: Traceback (most recent call last):
Notice: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns:   File "/srv/refinery-platform/deployment/bin/generate-superuser", line 39, in <module>
Notice: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns:     main()
Notice: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns:   File "/srv/refinery-platform/deployment/bin/generate-superuser", line 19, in main
Notice: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns:     with open("/home/ubuntu/s3-config") as inp:
Notice: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns: IOError: [Errno 2] No such file or directory: '/home/ubuntu/s3-config'
Error: /home/ubuntu/.virtualenvs/refinery-platform/bin/python /srv/refinery-platform/deployment/bin/generate-superuser > /srv/refinery-platform/refinery/core/fixtures/superuser.json.new returned 1 instead of one of [0]
Error: /Stage[main]/Refinery::Aws/Exec[generate_superuser_json]/returns: change from notrun to 0 failed: /home/ubuntu/.virtualenvs/refinery-platform/bin/python /srv/refinery-platform/deployment/bin/generate-superuser > /srv/refinery-platform/refinery/core/fixtures/superuser.json.new returned 1 instead of one of [0]
Notice: /Stage[main]/Refinery::Aws/Exec[copy_superuser_json]: Dependency Exec[generate_superuser_json] has failures: true
```

### Expected behavior
* Superuser to be created without errors

**Comment by scottx611x** [comment]
This was my own fault, closing
