### ISSUE TITLE
VisualizationTools can't be launched properly on DataSets with missing Data Files

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#2774]
* Specific code commit: 40deb27b2352af2a62d897e3763fc758e43271af
* Version of the web browser and OS: `Ubuntu 16.04 LTS Chrome`
* Environment where the error occurred : https://test.stemcellcommons.org/

### Steps to reproduce
Please list all the actions and the input data used:

1. Upload a `DataSet` that contains a Node pointing to a non-existent data file (lightning bolt icon)
![screen shot 2018-05-18 at 3 05 02 pm](https://user-images.githubusercontent.com/5629547/40253191-e05d2312-5aac-11e8-9e35-8379bf8c233c.png)

2. Launch any `VisualizationTool` on one or more of the `Nodes` in the `DataSet` pointing to a valid data file

### Observed behavior
* This is a side-effect of the [decision to include all of a DataSet's Node information in the input data sent to a `VisualizationTool` launch](https://github.com/refinery-platform/refinery-platform/issues/2413).
* `VisualizationTools` will launch but fail to fetch their input data due to the `Node(s)` in the `DataSet` that don't have data file urls
```
2018-05-18 15:00:14 ERROR    django.request:256 handle_uncaught_exception() - Internal Server Error: /api/v2/tools/558fee6b-ede6-49d0-be61-dc7d776dadb9/container_input_data/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/tool_manager/views.py", line 205, in container_input_data
    return JsonResponse(tool.get_container_input_dict())
  File "/srv/refinery-platform/refinery/tool_manager/models.py", line 505, in get_container_input_dict
    self.dataset.get_node_uuids()
  File "/srv/refinery-platform/refinery/tool_manager/models.py", line 548, in _get_detailed_nodes_dict
    for node in solr_response_json["nodes"]
  File "/srv/refinery-platform/refinery/tool_manager/models.py", line 548, in <dictcomp>
    for node in solr_response_json["nodes"]
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 1110, in get_file_url_from_node_uuid
    node.uuid
RuntimeError: Node with uuid: ef6bb532-8ba5-4e5b-a2df-6f434630df64 has no associated file url
``` 

### Expected behavior
* This shouldn't affect a Tool launch, because we're more so interested in the Nodes that a user has selected. It just so happens that after https://github.com/refinery-platform/refinery-platform/pull/2569 we now send information about every `Node` in a `DataSet` over to a `VisualizationTool`

**Comment by scottx611x** [comment]
Closed in https://github.com/refinery-platform/refinery-platform/commit/c74927404cdb5e88a473d7b70c8fb2cd7b312abf
