### ISSUE TITLE
Admin Interface - Unable to access user profiles

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#2802]
* Specific code commit: f36dfda3e6f60a24b2372d32fa34a0a8d9365470
* Version of the web browser and OS: Version 66.0.3359.181 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
beta site

### Steps to reproduce
Please list all the actions and the input data used:

1. Login as admin
2. Click on Core/User Profile

### Observed behavior
![screen shot 2018-06-04 at 1 07 27 pm](https://user-images.githubusercontent.com/9956764/40931248-6687340c-67f8-11e8-8101-09ea5aec1a39.png)

### Expected behavior
* See user profile interface
```
Internal Server Error: /admin/core/userprofile/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/base.py", line 1273, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 320, in result_list
    'results': list(results(cl))}
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 296, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 287, in __init__
    super(ResultList, self).__init__(*items)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 199, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 282, in lookup_field
    value = attr()
  File "/srv/refinery-platform/refinery/core/models.py", line 98, in __unicode__
    str(self.affiliation) + "): " +
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0443' in position 15: ordinal not in range(128)

Request repr(): 
<WSGIRequest
path:/admin/core/userprofile/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
 'CONTEXT_PREFIX': '',
 u'CSRF_COOKIE_USED': True,
 'DOCUMENT_ROOT': '/var/www',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'beta.stemcellcommons.org',
 'HTTP_REFERER': 'https://beta.stemcellcommons.org/admin/',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '134.174.140.196',
 'HTTP_X_FORWARDED_PORT': '443',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'PATH_INFO': u'/admin/core/userprofile/',
 'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/admin/core/userprofile/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '172.30.0.214',
 'REMOTE_PORT': '46646',
 'REQUEST_METHOD': 'GET',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/admin/core/userprofile/',
 'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
 'SCRIPT_NAME': u'',
 'SCRIPT_URI': 'http://beta.stemcellcommons.org/admin/core/userprofile/',
 'SCRIPT_URL': '/admin/core/userprofile/',
 'SERVER_ADDR': '172.30.0.130',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'beta.stemcellcommons.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
 'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.process_group': 'refinery',
 'mod_wsgi.queue_start': '1528131874227261',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 4),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f02c9633f30>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f02c9144738>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f02c9180130>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Note this works locally on develop.**

**Comment by scottx611x** [comment]
I think this is encapsulated in https://github.com/refinery-platform/refinery-platform/issues/2165
