### ISSUE TITLE
Certain user accounts fail to activate

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2917]
* Specific code commit: v1.6.5
* Version of the web browser and OS: unknown
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
```
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/registration/views.py", line 53, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/registration/views.py", line 56, in form_valid
    new_user = self.register(form)
  File "/srv/refinery-platform/refinery/core/views.py", line 1110, in register
    first_name, last_name, affiliation)
  File "/srv/refinery-platform/refinery/core/models.py", line 2104, in custom_create_inactive_user
    registration_profile.custom_send_activation_email(site)
  File "/srv/refinery-platform/refinery/core/models.py", line 2166, in custom_send_activation_email
    self.user.first_name, self.user.last_name),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

Request repr():
<WSGIRequest
path:/accounts/register/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'EelicanOr'], u'password1': [u'********************'], u'first_name': [u'\u044f\u0445\u0442 \u043a\u043b\u0443\u0431 \u043f\u0435\u043b\u0438\u043a\u0430\u043d '], u'last_name': [u'\u044f\u0445\u0442 \u043a\u043b\u0443\u0431 \u043f\u0435\u043b\u0438\u043a\u0430\u043d '], u'password2': [u'********************'], u'submit': [u'Register'], u'spam_filter': [u''], u'affiliation': [u'Duke University'], u'csrfmiddlewaretoken': <redacted>, u'email': [u'elkan2807@1mail.tw1.ru']}>,
COOKIES:{'csrftoken': <redacted>},
META:{'CONTENT_LENGTH': '404',
'CONTENT_TYPE': 'application/x-www-form-urlencoded',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': 'csrftoken=<redacted>,
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_PRAGMA': 'no-cache',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/accounts/register/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3223.8 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '37.212.217.177',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/accounts/register/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/accounts/register/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.30.0.46',
'REMOTE_PORT': '25516',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/accounts/register/.',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/accounts/register/',
'SCRIPT_URL': '/accounts/register/',
'SERVER_ADDR': '172.30.0.216',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1532772737724559',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f2afe8c11b0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2ad8c328a0>,
'wsgi.input': <mod_wsgi.Input object at 0x7f2afe8c11f0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No error

### Notes
May be related to #2557

**Comment by jkmarx** [comment]
Ref #2619

**Comment by hackdna** [comment]
Still an issue as of v1.6.9.1. It appears that this bug is preventing the account activation emails from going out if a user's name contains non-ASCII characters.
