### ISSUE TITLE
Handle ValueError in generate_solr_params

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2931]
* Specific code commit: v1.6.5
* Version of the web browser and OS: unknown
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
```
Internal Server Error: /api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 862, in get
    solr_params = generate_solr_params_for_assay(params, uuid)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 629, in generate_solr_params_for_assay
    return generate_solr_params(params, [assay_uuid], False, exclude_facets)
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 715, in generate_solr_params
    facet_filter = json.loads(facet_filter)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 1 column 87 (char 86)

Request repr():
<WSGIRequest
path:/api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/,
GET:<QueryDict: {u'data_set_uuid': [u'ce201ea2-2705-4dc1-9f0e-4a315bacb9ca'], u'sort': [u'REFINERY_ANALYSIS_UUID_940_474_s desc'], u'offset': [u'100'], u'limit': [u'100'], u'filter_attribute': [u'{"REFINERY_NAME_940_474_s":["int_mes_CD31%2BLYVE-_con1%2C%5C%5Crc-stor4.dfci.harvard.edu%5Crslab%5C1%5Cdata_store%5CNeil%5Cneil_rnaseq_6-13-17%5Cfastq%5CCD31_CON_1_26_17.fastq.gz%2CMouse%2CN%2FA%2CRNA-Seq%2Cmm10%2C6%2F13%2F2017%2CNeil%2CWT%2CCD31%2FLYVE1%2Cendothelial%2C"]}']}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1782439667.1533048077',
'_gid': 'GA1.2.998494014.1533311206',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'application/json, text/plain, */*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1782439667.1533048077; csrftoken=<redacted>; sessionid=<redacted>; _gid=GA1.2.998494014.1533311206',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/data_sets/ce201ea2-2705-4dc1-9f0e-4a315bacb9ca/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36',
'HTTP_X_CSRFTOKEN': <redacted>,
'HTTP_X_FORWARDED_FOR': '170.223.207.85',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/',
'QUERY_STRING': 'data_set_uuid=ce201ea2-2705-4dc1-9f0e-4a315bacb9ca&filter_attribute=%7B%22REFINERY_NAME_940_474_s%22:%5B%22int_mes_CD31%252BLYVE-_con1%252C%255C%255Crc-stor4.dfci.harvard.edu%255Crslab%255C1%255Cdata_store%255CNeil%255Cneil_rnaseq_6-13-17%255Cfastq%255CCD31_CON_1_26_17.fastq.gz%252CMouse%252CN%252FA%252CRNA-Seq%252Cmm10%252C6%252F13%252F2017%252CNeil%252CWT%252CCD31%252FLYVE1%252Cendothelial%252C%22%5D%7D&limit=100&offset=100&sort=REFINERY_ANALYSIS_UUID_940_474_s+desc',
'REMOTE_ADDR': '172.30.0.109',
'REMOTE_PORT': '57290',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/?data_set_uuid=ce201ea2-2705-4dc1-9f0e-4a315bacb9ca&filter_attribute=%7B%22REFINERY_NAME_940_474_s%22:%5B%22int_mes_CD31%252BLYVE-_con1%252C%255C%255Crc-stor4.dfci.harvard.edu%255Crslab%255C1%255Cdata_store%255CNeil%255Cneil_rnaseq_6-13-17%255Cfastq%255CCD31_CON_1_26_17.fastq.gz%252CMouse%252CN%252FA%252CRNA-Seq%252Cmm10%252C6%252F13%252F2017%252CNeil%252CWT%252CCD31%252FLYVE1%252Cendothelial%252C%22%5D%7D&limit=100&offset=100&sort=REFINERY_ANALYSIS_UUID_940_474_s+desc',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/',
'SCRIPT_URL': '/api/v2/assays/bf4a3bbc-6bdd-402a-a849-bc42b42dda30/files/',
'SERVER_ADDR': '172.30.0.216',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1533311530997217',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f2afe87fcf0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f2afebd45d0>,
'wsgi.input': <mod_wsgi.Input object at 0x7f2afe87ff70>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
Error is handled

### Notes
See also #2729 and #2710

**Comment by jkmarx** [comment]
Duplicate #2729

**Comment by hackdna** [comment]
Actually that issue refers to the same error but in a different function. I've updated the title to make it more explicit.
