### ISSUE TITLE
Internal Server Error in _check_max_running_containers

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2988]
* Specific code commit: v1.6.6
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
Refinery log:
```
Internal Server Error: /visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/refinery-platform/refinery/tool_manager/views.py", line 258, in _proxy_view
    visualization_tool.launch()
  File "/srv/refinery-platform/refinery/tool_manager/models.py", line 602, in launch
    self._check_max_running_containers()
  File "/srv/refinery-platform/refinery/tool_manager/models.py", line 540, in _check_max_running_containers
    if len(self.django_docker_client.list()) >= max_containers:
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/docker_utils.py", line 86, in list
    return self._containers_manager.list(filters)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/container_managers/docker_engine.py", line 182, in list
    return self._containers_client.list(all=True, filters=filters)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/models/containers.py", line 906, in list
    containers.append(self.get(r['Id']))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/models/containers.py", line 843, in get
    resp = self.client.api.inspect_container(container_id)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/api/container.py", line 730, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
NotFound: 404 Client Error: Not Found ("No such container: a5635b021effd13f1127ac5e6f1c46554abb796ae3929745eb6aa091446cb72b")

Request repr():
<WSGIRequest
path:/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1570110784.1528822336',
'_gid': 'GA1.2.733805853.1536097967',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTENT_LENGTH': '0',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1570110784.1528822336; _gid=GA1.2.733805853.1536097967; csrftoken=<redacted>; sessionid=<redacted>',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_ORIGIN': 'https://beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '134.174.140.198',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.30.0.124',
'REMOTE_PORT': '35204',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming',
'SCRIPT_URL': '/visualizations/Intervene-1c518534-30ea-407f-b552-b8349329ab9d/__sockjs__/n=BmaAnUHZ5PjAcwMYYW/751/jrtr5ykm/xhr_streaming',
'SERVER_ADDR': '172.30.0.102',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1536110178196179',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f80e4b50e70>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f80cfe7e120>,
'wsgi.input': <mod_wsgi.Input object at 0x7f80e49a5070>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No internal server error

**Comment by jkmarx** [comment]
@scottx611x Confirm if it's still used.
