### ISSUE TITLE
Internal Server Error in _proxy_view

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2989]
* Specific code commit: v1.6.6
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
Refinery log:
```
Internal Server Error: /visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/refinery-platform/refinery/tool_manager/views.py", line 262, in _proxy_view
    request, container_name, url
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 113, in _proxy_view
    return self._internal_proxy_view(request, container_url, url)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/proxy.py", line 102, in _internal_proxy_view
    return view(request, path=path_url)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/revproxy/views.py", line 204, in dispatch
    proxy_response = self._created_proxy_response(request, path)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/revproxy/views.py", line 161, in _created_proxy_response
    preload_content=False)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
ProtocolError: ('Connection aborted.', BadStatusLine("''",))

Request repr():
<WSGIRequest
path:/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1765560539.1510593547',
'_gid': 'GA1.2.1456233752.1536141149',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTENT_LENGTH': '0',
'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9,de;q=0.8',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1765560539.1510593547; _gid=GA1.2.1456233752.1536141149; csrftoken=<redacted>; sessionid=<redacted>',
'HTTP_DNT': '1',
'HTTP_HOST': 'beta.stemcellcommons.org',
'HTTP_ORIGIN': 'https://beta.stemcellcommons.org',
'HTTP_REFERER': 'https://beta.stemcellcommons.org/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '134.174.140.195',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.30.0.124',
'REMOTE_PORT': '14524',
'REQUEST_METHOD': 'POST',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://beta.stemcellcommons.org/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr',
'SCRIPT_URL': '/visualizations/Intervene-ba4c865e-4ab7-49c0-b725-77b90ad22d18/__sockjs__/n=DQG6Cqyp87pb7BbCC3/349/5lr_gl88/xhr',
'SERVER_ADDR': '172.30.0.102',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'beta.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'beta.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1536164720885320',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f55a67cd2f0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f55cc5296c0>,
'wsgi.input': <mod_wsgi.Input object at 0x7f55cc82a0b0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No internal server error

**Comment by jkmarx** [comment]
@scottx611x Confirm if still used.
