### ISSUE TITLE
Internal Server Error: /data_set_manager/import/metadata-table-form/

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3003]
* Specific code commit: 26369d0 (?)
* Version of the web browser and OS: N/A
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
```
Internal Server Error: /data_set_manager/import/metadata-table-form/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 455, in get
    return render(request, self.template_name)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: data_set_manager/metadata-table-import.html

Request repr():
<WSGIRequest
path:/data_set_manager/import/metadata-table-form/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.1354209348.1507481536',
'_gid': 'GA1.2.670412009.1536864258',
'csrftoken': <redacted>,
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.1354209348.1507481536; _gid=GA1.2.670412009.1536864258; csrftoken=<redacted>; sessionid=<redacted>',
'HTTP_HOST': 'test.stemcellcommons.org',
'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '134.174.140.196',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/data_set_manager/import/metadata-table-form/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/data_set_manager/import/metadata-table-form/',
'QUERY_STRING': '',
'REMOTE_ADDR': '10.0.0.202',
'REMOTE_PORT': '51182',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/data_set_manager/import/metadata-table-form/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://test.stemcellcommons.org/data_set_manager/import/metadata-table-form/',
'SCRIPT_URL': '/data_set_manager/import/metadata-table-form/',
'SERVER_ADDR': '10.0.0.252',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'test.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'test.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1536940194471426',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7fd5adf2acf0>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7fd5ade48918>,
'wsgi.input': <mod_wsgi.Input object at 0x7fd5adf2a970>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No internal server error

**Comment by jkmarx** [comment]
Reference https://github.com/refinery-platform/refinery-platform/issues/2681

**Comment by jkmarx** [comment]
I introduced this error uploading a data_set with a dash in the filename

**Comment by hackdna** [comment]
No, that's a [different error](https://github.com/refinery-platform/refinery-platform/issues/3004)
