### ISSUE TITLE
ReadTimeout in Tool.is_running()

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3046]
* Specific code commit: v1.6.6.2
* Version of the web browser and OS: unknown
* Environment where the error occurred: AWS

### Steps to reproduce
Unknown, error report received by email

### Observed behavior
Refinery log:
```
Internal Server Error: /visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/refinery-platform/refinery/tool_manager/views.py", line 257, in _proxy_view
    if not visualization_tool.is_running():
  File "/srv/refinery-platform/refinery/tool_manager/models.py", line 456, in is_running
    self.container_name
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/docker_utils.py", line 83, in lookup_container_url
    return self._containers_manager.get_url(container_name)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django_docker_engine/container_managers/docker_engine.py", line 134, in get_url
    container = self._containers_client.get(container_name)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/models/containers.py", line 843, in get
    resp = self.client.api.inspect_container(container_id)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/api/container.py", line 730, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='172.30.1.22', port=2375): Read timed out. (read timeout=60)

Request repr():
<WSGIRequest
path:/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{'_ga': 'GA1.2.456711046.1537888310',
'_gid': 'GA1.2.956569237.1538497270',
'csrftoken': <redacted>,
'isa_tab_url': 'https://hsci.stemcellcommons.org/media/file_store/b6/94/chip-seq_in_mouse_kidney.zip',
'messages': '1d935b7356af508aefd9f8f0b73476ae6eda09ee$[["__json_message",0,25,"If you don\'t want to fill your profile out now, you can go to the <a href=\'/\'>homepage</a>.","safe"]]',
'sessionid': <redacted>},
META:{'CONTEXT_DOCUMENT_ROOT': '/var/www',
'CONTEXT_PREFIX': '',
u'CSRF_COOKIE': <redacted>,
'DOCUMENT_ROOT': '/var/www',
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': '*/*',
'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9,fr;q=0.8',
'HTTP_CONNECTION': 'keep-alive',
'HTTP_COOKIE': '_ga=GA1.2.456711046.1537888310; csrftoken=<redacted>; sessionid=<redacted>; messages="1d935b7356af508aefd9f8f0b73476ae6eda09ee$[[\\"__json_message\\"\\0540\\05425\\054\\"If you don\'t want to fill your profile out now\\054 you can go to the <a href=\'/\'>homepage</a>.\\"\\054\\"safe\\"]]"; isa_tab_url="https://hsci.stemcellcommons.org/media/file_store/b6/94/chip-seq_in_mouse_kidney.zip"; _gid=GA1.2.956569237.1538497270',
'HTTP_HOST': 'hsci.stemcellcommons.org',
'HTTP_REFERER': 'https://hsci.stemcellcommons.org/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/',
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36',
'HTTP_X_FORWARDED_FOR': '134.174.21.189',
'HTTP_X_FORWARDED_PORT': '443',
'HTTP_X_FORWARDED_PROTO': 'https',
'PATH_INFO': u'/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/',
'PATH_TRANSLATED': '/srv/refinery-platform/refinery/config/wsgi_aws.py/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/',
'QUERY_STRING': '',
'REMOTE_ADDR': '172.30.0.18',
'REMOTE_PORT': '42092',
'REQUEST_METHOD': 'GET',
'REQUEST_SCHEME': 'http',
'REQUEST_URI': '/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/',
'SCRIPT_FILENAME': '/srv/refinery-platform/refinery/config/wsgi_aws.py',
'SCRIPT_NAME': u'',
'SCRIPT_URI': 'http://hsci.stemcellcommons.org/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/',
'SCRIPT_URL': '/visualizations/CaleydoLineUp-faba14bc-0867-4e09-88f2-dd00c72c6e0d/',
'SERVER_ADDR': '172.30.0.207',
'SERVER_ADMIN': '[no address given]',
'SERVER_NAME': 'hsci.stemcellcommons.org',
'SERVER_PORT': '80',
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SIGNATURE': '',
'SERVER_SOFTWARE': 'Apache/2.4.7 (Ubuntu)',
'mod_wsgi.application_group': 'hsci.stemcellcommons.org|',
'mod_wsgi.callable_object': 'application',
'mod_wsgi.enable_sendfile': '0',
'mod_wsgi.handler_script': '',
'mod_wsgi.input_chunked': '0',
'mod_wsgi.listener_host': '',
'mod_wsgi.listener_port': '80',
'mod_wsgi.process_group': 'refinery',
'mod_wsgi.queue_start': '1538500475738271',
'mod_wsgi.request_handler': 'wsgi-script',
'mod_wsgi.script_reloading': '1',
'mod_wsgi.version': (3, 4),
'wsgi.errors': <mod_wsgi.Log object at 0x7f1a68cc4070>,
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f1a524f6eb8>,
'wsgi.input': <mod_wsgi.Input object at 0x7f1a68a72cb0>,
'wsgi.multiprocess': False,
'wsgi.multithread': True,
'wsgi.run_once': False,
'wsgi.url_scheme': 'http',
'wsgi.version': (1, 0)}>
```

### Expected behavior
No internal server error

**Comment by hackdna** [comment]
Still an issue in v1.6.7
