### ISSUE TITLE
HTTP 500 in site_profiles API due to DoesNotExist in SiteProfileViewSet.get()

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#3200]
* Specific code commit: 15bf05c
* Version of the web browser and OS: Chrome 72 on OS X 10.14.3
* Environment where the error occurred: Vagrant

### Steps to reproduce
1. Provision a Vagrant VM from scratch
1. Open the home page in a web browser

### Observed behavior
Browser console:
```
GET http://192.168.50.50:8000/api/v2/site_profiles/ 500 (INTERNAL SERVER ERROR)
```

Refinery error log:
```
2019-02-06 10:43:44 ERROR    django.request:256 handle_uncaught_exception() - Internal Server Error: /api/v2/site_profiles/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/vagrant/refinery/core/views.py", line 1087, in get
    site_profile = SiteProfile.objects.get(site=get_current_site(request))
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: SiteProfile matching query does not exist.
```

### Expected behavior
No internal server error

**Comment by jkmarx** [comment]
Resolved with pull request https://github.com/refinery-platform/refinery-platform/pull/3197
