### ISSUE TITLE
Unable to upload RFC file

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#3359]
Specific code commit: fdf35ba
Version of the web browser and OS: Firefox 66.0.3
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance):
https://test.stemcellcommons.org/

### Steps to reproduce
Please list all the actions and the input data used:

1. Upload RFC local or test file https://github.com/refinery-platform/refinery-platform/wiki/Testing-Requirements-before-Release#isa-tab-metadata-tab 

### Observed behavior
Upload fails for both rfc files but worked for other isatabs. 
Note, uploading the data files for the local rfc work fine.

response: 
```
config:
data: FormData {}
headers:
Accept: "application/json, text/plain, */*"
Content-Type: undefined
X-CSRFToken: "removed"
X-Requested-With: "XMLHttpRequest"
method: "POST"
url: "/data_set_manager/import/isa-tab-form/"
data: "ISA-Tab import Failure:  An error occurred (403) when calling the HeadObject operation: Forbidden"
status: 400
statusText: "BAD REQUEST"
```

### Expected behavior
No error and should upload

**Comment by jkmarx** [comment]
Uploading the RFC file works fine locally and on the HSCI site.

**Comment by hackdna** [comment]
What does the server error log say?

**Comment by jkmarx** [comment]
@hackdna The files are names rfc-test and rfc-test-local (see link for download)
refinery-errors.log

```2019-04-30 11:08:22 ERROR    data_set_manager.views:404 post() - ISA-Tab import Failure:  Traceback (most recent call last):
  File "/srv/refinery-platform/refinery/data_set_manager/views.py", line 390, in post
    existing_data_set_uuid=existing_data_set_uuid
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/celery/app/task.py", line 428, in __call__
    return self.run(*args, **kwargs)
  File "/srv/refinery-platform/refinery/data_set_manager/tasks.py", line 200, in parse_isatab
    fileStoreItem.datafile
  File "/srv/refinery-platform/refinery/data_set_manager/utils.py", line 370, in calculate_checksum
    block = f.read(bufsize)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/files/utils.py", line 16, in <lambda>
    read = property(lambda self: self.file.read)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/db/models/fields/files.py", line 51, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/files/storage.py", line 37, in open
    return self._open(name, mode)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/storages/backends/s3boto3.py", line 410, in _open
    f = S3Boto3StorageFile(name, mode, self)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/storages/backends/s3boto3.py", line 69, in __init__
    self.obj.load()
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by hackdna** [comment]
This is most likely due to a dangling ISA archive reference (from a previously uploaded data set) that points to an object that exists in the prod bucket but not in the test bucket. You need to copy the objects from prod bucket to test bucket in order to avoid this issue: https://github.com/stemcellcommons/stemcellcommons/wiki#refinery-platform

**Comment by jkmarx** [comment]
See above comment. Issue resolved after following the above steps.

**Comment by hackdna** [comment]
I'm testing an update that should help in these situations: https://github.com/refinery-platform/refinery-platform/tree/hackdna/checksum-error-handling
