### ISSUE TITLE
Data Set Search Error

### ISSUE THREAD

**Issue by gmnelson** [refinery-platform/refinery-platform#3396]
* Specific code commit: 4c0b2fb
* Version of the web browser and OS: Chrome/Firefox, macOS
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): hsci.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Search for anything (e.g "atac-seq") within the Data Sets card on the dashboard

### Observed behavior

![image](https://user-images.githubusercontent.com/23487494/59452610-14a21980-8ddc-11e9-931d-dbc774dacf47.png)

* Also, matching data sets are not returned

### Expected behavior
* No error and matching data sets returned

**Comment by jkmarx** [comment]
Solr logs
```
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "edge_ngram": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'solr.WordDel
imiterGraphFilterFactory'. Schema file is /srv/refinery-platform/refinery/solr/core/conf/schema.xml
        at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:596)
        at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:175)
        at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55)
        at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:69)
        at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:104)
        at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:75)
        ... 8 more
```

**Comment by jkmarx** [comment]
@gmnelson I'm not seeing this issue on https://test.stemcellcommons.org/dashboard/

**Comment by jkmarx** [comment]
Response 
```
<title>Error 500 {msg=SolrCore &apos;core&apos; is not available due to init failure: Could not load conf for core core: Plugin init failure for [schema.xml] fieldType &quot;edge_ngram&quot;: Plugin init failure for [schema.xml] analyzer/filter: Error loading class &apos;solr.WordDelimiterGraphFilterFactory&apos;. Schema file is /srv/refinery-platform/refinery/solr/core/conf/schema.xml,trace=org.apache.solr.common.SolrException: SolrCore &apos;core&apos; is not available due to init failure: Could not load conf for core core: Plugin init failure for [schema.xml] fieldType &quot;edge_ngram&quot;: Plugin init failure for [schema.xml] analyzer/filter: Error loading class &apos;solr.WordDelimiterGraphFilterFactory&apos;. Schema file is /srv/refinery-platform/refinery/solr/core/conf/schema.xml
	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:974)
	at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:250)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:417)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:214)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:179)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Could not load conf for core core: Plugin init failure for [schema.xml] fieldType &quot;edge_ngram&quot;: Plugin init failure for [schema.xml] analyzer/filter: Error loading class &apos;solr.WordDelimiterGraphFilterFactory&apos;. Schema file is /srv/refinery-platform/refinery/solr/core/conf/schema.xml
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:80)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:721)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:443)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:434)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	... 1 more
```

**Comment by jkmarx** [comment]
Could not reproduce locally, commit 4d13dffbfe97a16ede6eaf055c8e600d57566a54   (pre-ubuntu upgrade)
