### ISSUE TITLE
data_set_manager has test with non-determinstic behavior

### ISSUE THREAD

**Issue by ilan-gold** [refinery-platform/refinery-platform#3444]
* Specific code commit: 
* Version of the web browser and OS: 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 

### Steps to reproduce
Please list all the actions and the input data used:

1. Move the actual test functionality into its own function
2. Run that function inside a while-true loop inside the actual test until it fails

### Observed behavior
* The test test_get_with_study_uuid_returns_file_uuid_field fails randomly because the order of nodes serialized/returned is non-deterministic
* This causes the `first_node` to sometimes be a node lacking a `file_uuid` field.

`Error Traceback (most recent call last):
  File "/vagrant/refinery/data_set_manager/test_views.py", line 815, in test_get_with_study_uuid_returns_file_uuid_field
    self.get_with_study_uuid_returns_file_uuid_field()
  File "/vagrant/refinery/data_set_manager/test_views.py", line 830, in get_with_study_uuid_returns_file_uuid_field
    raise e
AttributeError: 'NoneType' object has no attribute 'uuid'`

### Expected behavior
* The test should always pass

**Comment by ilan-gold** [comment]
@hackdna do you know why we get the first node to test as opposed to some other one? i don't think i have a great understanding of things, but i can tell that there are nodes created for this dataset that lack a `file_item` field
