### ISSUE TITLE
500 Error UserDoesNotExist

### ISSUE THREAD

**Issue by ilan-gold** [refinery-platform/refinery-platform#3463]
* Specific code commit: 
* Version of the web browser and OS: Firefox 
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): VM

### Steps to reproduce
Please list all the actions and the input data used:

1. Open a window and navigate to a dataset
<img width="1680" alt="Screen Shot 2019-10-09 at 3 32 20 PM" src="https://user-images.githubusercontent.com/43999641/66514047-61f07800-eaaa-11e9-90cf-db17cc605462.png">

2. Open a new window
<img width="1680" alt="Screen Shot 2019-10-09 at 3 32 29 PM" src="https://user-images.githubusercontent.com/43999641/66514060-687eef80-eaaa-11e9-83de-e07f52ea8da4.png">

3. Logout in this window
<img width="1680" alt="Screen Shot 2019-10-09 at 3 33 43 PM" src="https://user-images.githubusercontent.com/43999641/66514069-6ddc3a00-eaaa-11e9-9300-fb7223237735.png">

4. Navigate to the other window (with the dataset)
5. Refresh the page
<img width="1680" alt="Screen Shot 2019-10-09 at 3 34 27 PM" src="https://user-images.githubusercontent.com/43999641/66514094-7c2a5600-eaaa-11e9-9d2e-a82d59d9dcef.png">

### Observed behavior
500 Error displayed in browser/log

User is AnonymousUser in browser

```2019-10-09 15:53:48 ERROR    django.request:256 handle_uncaught_exception() - Internal Server Error: /data_sets/52e8a1af-7bda-4c93-972b-0fb01ca6c1e2/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/vagrant/refinery/core/views.py", line 211, in data_set
    if not request.user.has_perm('core.read_meta_dataset', data_set):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 500, in has_perm
    return _user_has_perm(self, perm, obj=obj)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 281, in _user_has_perm
    if backend.has_perm(user, perm, obj):
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/backends.py", line 80, in has_perm
    support, user_obj = check_support(user_obj, obj)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/backends.py", line 47, in check_support
    user_support, user_obj = check_user_support(user_obj)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/guardian/backends.py", line 37, in check_user_support
    user_obj = User.objects.get(**lookup)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
```

### Expected behavior
A Refinery error page

**Comment by jkmarx** [comment]
Root cause Ref #1103
