### ISSUE TITLE
Celery Chain Does Not Fail

### ISSUE THREAD

**Issue by ilan-gold** [refinery-platform/refinery-platform#3490]
* Specific code commit: https://github.com/refinery-platform/refinery-platform/tree/d60004dff050f377c659e0b0cb661ab9ab75e363
* Version of the web browser and OS: Any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
AWS
### Steps to reproduce
Please list all the actions and the input data used:
This actually appears to be a broad based problem with celery (you will need to move `fail` and `succeed` into a `tasks.py` file so they are discovered):

```
import os;
import django;
os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings.dev'
django.setup()
from celery import chain

@task
def fail():
    raise IndexError
@task
def succeed()
    print 'foo'

t = chain( fail.subtask(), succeed.subtask(), time_limit=20)
t.delay()
```

### Observed behavior
```
2019-11-15 11:31:13,332 ERROR    celery.worker.job:282 log() - Task data_set_manager.tasks.generate_auxiliary_file[29c3d044-7579-429b-bb91-7ab688f3788a] raised unexpected: SamtoolsError()
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/refinery-platform/refinery/data_set_manager/tasks.py", line 307, in generate_auxiliary_file
    auxiliary_file_path = generate_bam_index(datafile_path)
  File "/srv/refinery-platform/refinery/data_set_manager/tasks.py", line 342, in generate_bam_index
    pysam.index(bytes(temp_bam_file_path), bytes(bam_index_file_path))
  File "/home/ubuntu/.virtualenvs/refinery-platform/local/lib/python2.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
SamtoolsError

```

There is a failure in the chain, but the whole chian does not fail and instead hangs.
```
2019-11-15 14:28:45,100 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:28:45,230 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'
2019-11-15 14:28:50,957 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:28:51,065 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'
2019-11-15 14:28:57,068 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:28:57,171 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'
2019-11-15 14:29:02,200 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:29:02,307 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'
2019-11-15 14:29:09,076 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:29:09,188 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'
2019-11-15 14:29:15,078 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:29:15,182 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'
2019-11-15 14:29:20,953 INFO     analysis_manager.tasks:332 run_analysis[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Executing Analysis with UUID: 5bad41e2-55c3-48e5-b45b-6264d576a948
2019-11-15 14:29:21,050 DEBUG    analysis_manager.tasks:167 _attach_workflow_outputs[eb3b962d-3f5f-4b08-ad57-dd3fd46e6fd7] - Auxiliary file import and generation running for analysis 'Kallisto RNA-seq (SE) Quantification - Human - 2019/11/15 09:46:34 - Ilangold - ilangold - Galaxy workflow execution for: Kallisto RNA-seq (SE) Quantification - Human'

```
I think this issue https://github.com/celery/celery/issues/1014 has never been resolved with Celery at large (a pull request at the bottom is still open).  This means chains hang when one task fails since the AsyncResult points at the last task.  The solution will be to do a similar thing to what we do with `FileImportTask` and just have a post-completion action (I can't believe I didn't think of this before).

### Expected behavior
* The chain should fail

**Comment by ilan-gold** [comment]
see:

https://stackoverflow.com/a/21106596

https://stackoverflow.com/questions/11508112/retrying-celery-failed-tasks-that-are-part-of-a-chain

I think it's largely irrelevant though since we can jsut run this as a post-processing task, which makes more sense anyway in my opinion.

**Comment by ilan-gold** [comment]
Although this is an issue with Celery, this will be left untouched.  We will continue to use the chain but not monitor it.
