### ISSUE TITLE
Analysis is reported as finished successfully while still running in Galaxy when AJAX call to analysis_status view results in a server error

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#451]
Sample traceback:

```
2014-09-23 02:13:50 ERROR    base handle_uncaught_exception: Internal Server Error: /analysis_manager/8f4d954c-9417-4e8b-a3aa-c03ab11bde87/
Traceback (most recent call last):
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/srv/scc/apps/refinery-platform/refinery/analysis_manager/views.py", line 73, in analysis_status
    ret_json['execution'] = status.execution_status()
  File "/srv/scc/apps/refinery-platform/refinery/analysis_manager/models.py", line 54, in execution_status
    history = connection.histories.show_history(self.analysis.history_id)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/bioblend/galaxy/histories/__init__.py", line 70, in show_history
    return Client._get(self, id=history_id, contents=contents, params=params)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 99, in _get
    return self._get_retry(url, params)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 139, in _get_retry
    r = self.gi.make_get_request(url, params)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 58, in make_get_request
    r = requests.get(url, verify=self.verify, params=params)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 448, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 554, in send
    r = adapter.send(request, **kwargs)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/adapters.py", line 359, in send
    timeout=timeout
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 722, in _validate_conn
    conn.connect()
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 195, in connect
    conn = self._new_conn()
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 125, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by scottx611x** [comment]
Handled in new analysis monitoring rewrite
