### ISSUE TITLE
Handle ConnectionError exception in core.views.solr_select()

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#814]
Commit 7bfb7ccc.
## Steps to reproduce
1. Stop Solr
2. Access any data set (`/data_sets/<UUID>/#/files/browse`)
## Observed behavior

Browser console log shows HTTP 500 errors:

```
/solr/data_set_manager/select/?q=dj…%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:false&_=1449677759724 500 (INTERNAL SERVER ERROR)
/solr/data_set_manager/select/?q=dj…d%20Array%20Data%20Matrix%20File%22)&fq=is_annotation:true&_=1449677759726 500 (INTERNAL SERVER ERROR)
/solr/data_set_manager/select/?q=dj…actor_Value_1746_882_s&sort=REFINERY_NAME_1746_882_s%20asc&_=1449677759727 500 (INTERNAL SERVER ERROR)
```

Server log shows ConnectionError:

```
Wed Dec 09 11:16:03 2015] [error] 2015-12-09 11:16:03 ERROR    django.request:212 handle_uncaught_exception() - Internal Server Error: /solr/data_set_manager/select/
[Wed Dec 09 11:16:03 2015] [error] Traceback (most recent call last):
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
[Wed Dec 09 11:16:03 2015] [error]     response = callback(request, *callback_args, **callback_kwargs)
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/apps/refinery-platform/refinery/core/views.py", line 591, in solr_select
[Wed Dec 09 11:16:03 2015] [error]     fullResponse = requests.get(url, params=data)
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/api.py", line 69, in get
[Wed Dec 09 11:16:03 2015] [error]     return request('get', url, params=params, **kwargs)
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/api.py", line 50, in request
[Wed Dec 09 11:16:03 2015] [error]     response = session.request(method=method, url=url, **kwargs)
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
[Wed Dec 09 11:16:03 2015] [error]     resp = self.send(prep, **send_kwargs)
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
[Wed Dec 09 11:16:03 2015] [error]     r = adapter.send(request, **kwargs)
[Wed Dec 09 11:16:03 2015] [error]   File "/srv/scc/virtualenvs/refinery-platform/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
[Wed Dec 09 11:16:03 2015] [error]     raise ConnectionError(err, request=request)
[Wed Dec 09 11:16:03 2015] [error] ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```
## Expected behavior

ConnectionError exception should be handled on the server side with appropriate message logged and sent to the client side (no HTTP 500 errors should be generated).

**Comment by mccalluc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Au20IB45&#x2F;30-814"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #814</a>

**Comment by jkmarx** [comment]
The view page is no longer used (it was removed in the file browser 2 transition).
